All api groups
kyma-project/busola pull request #1123
Opened 2022-03-22 07:32 UTC by qbalukom

2022-03-28 10:07 UTC, dariadomagala requested changes
You cannot type anything in the input now, it's automatically added as a nwe api gruop etc

2022-03-29 06:05 UTC, qbalukom commented
/retest

2022-03-29 06:43 UTC, dariadomagala requested changes
Now you can type in some values, but those are not being added to the list, nothing happens. I cannot add a verb that's not on the list and it was a reason why we've chosen this component.

2022-03-29 06:43 UTC, dariadomagala commented on core-ui/src/components/Predefined/Create/Roles/helpers.js
> +  unique(groupVersions.map(extractApiGroup)).map(g =>
can we please add either `?` before map, or `|| []` at the end? I think it's the most common cause when it comes to crashing UIs in our code 😄 

(please also apply in other places, it doesn't make sense to comment it all - also for 'some', 'filter' etc)

2022-03-29 06:43 UTC, dariadomagala commented on core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
> +                console.log('onSelectionChange', selected);
nope

2022-03-29 06:44 UTC, qbalukom commented on core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
> +                console.log('onSelectionChange', selected);
oops

2022-03-29 07:36 UTC, qbalukom commented
/retest

2022-03-29 08:04 UTC, qbalukom commented
/retest

2022-03-29 08:10 UTC, qbalukom commented
/retest

2022-03-29 08:19 UTC, qbalukom commented
/retest

2022-03-29 08:24 UTC, qbalukom commented
/retest

2022-03-29 08:36 UTC, qbalukom commented
/retest

2022-03-29 09:06 UTC, dariadomagala approved these changes

2022-03-29 09:08 UTC, grego952 approved these changes

2022-03-29 09:16 UTC, merged