Add default prometheus address
kyma-project/busola pull request #1139
Opened 2022-03-23 09:48 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

Resolves #1128

2022-03-23 17:15 UTC, qbalukom requested changes

2022-03-23 17:15 UTC, qbalukom commented on core-ui/src/shared/components/StatsGraph/StatsPanel.js
> +  let path = features.PROMETHEUS?.config?.path;
wouldn't it be better to read the path inside the `usePrometheus` hook? It's read from microfrontend context anyway - passing the path through these components seems to only add unnecessary complexity

2022-03-23 17:15 UTC, qbalukom commented on core/src/assets/defaultConfig.json
> +          "path": "api/v1/namespaces/kyma-system/services/monitoring-prometheus:web/proxy/api/v1"
do we need actually the whole path?
both the prefix (`api/v1/namespaces/kyma-system/services/`) and the suffix (`/proxy/api/v1`) are very unlikely to change - as they're part of the kubernetes and prometheus implementations respectively.
The only two parts that can easily change on a per-cluster basis are service name and port name. I feel that would be enough. Either as a single value (`monitoring-prometheus:web`) or two, one for service name (`monitoring-prometheus`) one for port (`web`)

2022-03-24 09:24 UTC, grego952 commented on docs/features.md
> +- **VISUAL_RESOURCES** – configures if the resource graphs should be rendered at resources details views.
```suggestion
- **VISUAL_RESOURCES** – determines if the resource graphs should be rendered at a resource details view.
```

2022-03-24 09:27 UTC, grego952 approved these changes

2022-03-24 09:59 UTC, dariadomagala commented
/retest

2022-03-24 10:44 UTC, qbalukom approved these changes

2022-03-24 10:44 UTC, merged