Change base image to unprivileged nginx
kyma-project/busola pull request #1175
Opened 2022-03-30 09:47 UTC by KaiReichart

Currently, the web container is running as root. With usage of the nginx unprivileged image, the container can run with an arbitrary user-id and does not need to be run as root anymore.

Changes proposed in this pull request:

- Change base image to `nginx-unprivileged`

2022-03-30 10:00 UTC, mrCherry97 commented
/test all

2022-03-30 10:07 UTC, KaiReichart commented
@mrCherry97 It looks like the docker image is not being built, am I missing something here?

2022-04-05 07:15 UTC, mrCherry97 requested changes
Hi @KaiReichart !
When you are editing just Dockerfile you don't have to bu,p deployments, let's bring PR numbers back and we can check the tests. Thanks!

2022-04-05 07:15 UTC, mrCherry97 commented on resources/backend/deployment.yaml
> -          image: eu.gcr.io/kyma-project/busola-backend:PR-1145
You have to bring back `PR-1145`

2022-04-05 07:15 UTC, mrCherry97 commented on resources/web/deployment.yaml
> -          image: eu.gcr.io/kyma-project/busola-web:PR-1174
Yout have to bring back `PR-1174`

2022-04-06 09:03 UTC, KaiReichart commented on resources/backend/deployment.yaml
> -          image: eu.gcr.io/kyma-project/busola-backend:PR-1145
done thx

2022-04-06 09:03 UTC, KaiReichart commented on resources/web/deployment.yaml
> -          image: eu.gcr.io/kyma-project/busola-web:PR-1174
done thx

2022-04-06 09:05 UTC, KaiReichart commented
@mrCherry97 changed it back, thx. 
However, I don't really understand how the tests will bring any value if the Dockerfile is not being used for the tests... 

Maybe the images should also be built and tested when the Dockerfile changes?
Because now the tests don't really test the changes of the PR, right?

2022-04-06 09:51 UTC, mrCherry97 commented
/test all

2022-04-06 09:53 UTC, mrCherry97 commented
@KaiReichart 
When you change Dockerfile we need to test `pre-busola-web` because we are using docker images for testing and development, so we need to know that images are building and deploying well.

2022-04-12 11:37 UTC, KaiReichart commented
@mrCherry97 can this be merged now? Or is it missing something?

2022-04-13 07:47 UTC, Wawrzyn321 commented
@KaiReichart yeah, it's missing something - my review. On it right now!

2022-04-13 08:23 UTC, Wawrzyn321 approved these changes

2022-04-13 08:34 UTC, KaiReichart commented
Thanks @Wawrzyn321 ! Now its saying `Requested changes must be addressed to merge this pull request.`  
How do we resolve this? I had incorporated the requested changes already, but it seems like GitHub didn't notice...

2022-04-13 08:36 UTC, mrCherry97 approved these changes

2022-04-13 08:36 UTC, Wawrzyn321 commented
It looks like @mrCherry97 needs to approve, as he requested some changes.

2022-04-13 08:36 UTC, merged

2022-04-13 08:36 UTC, mrCherry97 commented
Hi @KaiReichart and @Wawrzyn321 
Changes approved 😄

2022-04-13 08:37 UTC, KaiReichart commented
nice, thanks guys! See you in the next PR ;)

2022-04-13 14:11 UTC, mrCherry97 commented
/test all