Introduce a name generator
kyma-project/busola pull request #1209
Opened 2022-04-05 05:47 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-04-05 09:59 UTC, akucharska reviewed
Very good job. I have just few more proposition for removal: 
broken, corrupt, critical, damaged, embarrassed, fake, harmful, horrible, lame, loathsome, naive, pitiful, sinful

2022-04-05 09:59 UTC, akucharska commented on core-ui/src/shared/utils/randomNamesGenerator/words.js
>    'fat',
I would also remove fat

2022-04-06 08:17 UTC, mrCherry97 requested changes
Generating random name should be disabled on `Edit` panel.
![image](https://user-images.githubusercontent.com/46759954/161924914-8f7de91c-f06b-4ba1-87c8-4a7d10fc9f86.png)
![image](https://user-images.githubusercontent.com/46759954/161924976-dee762a0-5763-436d-9dbd-d4cc4f06dcf7.png)
The same is in Jobs when I click generate on Container name:
![image](https://user-images.githubusercontent.com/46759954/161926784-839ee580-32af-4f57-bc57-c50572e34479.png)
I think in ReplicaSets we have to allow generate names for containers as in Jobs
![image](https://user-images.githubusercontent.com/46759954/161927130-0ce4fcce-90f3-4ba4-87a7-2669fe4cf843.png)
Gateways -> Ports I think the same comment as ReplicaSets
![image](https://user-images.githubusercontent.com/46759954/161927516-08d78830-63ac-460b-ab3a-ab198f1ac08e.png)
RoleBindings and ClusterRoleBindings don't have a name generator
![image](https://user-images.githubusercontent.com/46759954/161927952-42057650-b46d-407e-b774-09d5a07cc9b1.png)

2022-04-06 12:01 UTC, mrCherry97 requested changes
```
src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
@kyma-project/core-ui:   Line 3:10:  'MessageStrip' is defined but never used  no-unused-vars
@kyma-project/core-ui:   Line 6:10:  'K8sNameField' is defined but never used  no-unused-vars
@kyma-project/core-ui: src/shared/components/Deployment/Containers.js
@kyma-project/core-ui:   Line 15:14:  'i18n' is assigned a value but never used  no-unused-vars
```

2022-04-06 12:03 UTC, mrCherry97 commented on core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.scss
> +}
You can use `.fd-display-flex` instead custom className with the same functionality.

2022-04-07 09:24 UTC, mrCherry97 requested changes

2022-04-07 09:24 UTC, mrCherry97 commented on core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
> +          style={{ display: 'block' }}
There is a problem with styling in Addons
![image](https://user-images.githubusercontent.com/46759954/162166444-17970270-a954-405c-9aef-38c26b3e617a.png)

2022-04-07 09:51 UTC, mrCherry97 approved these changes

2022-04-07 09:56 UTC, Wawrzyn321 approved these changes

2022-04-07 10:11 UTC, merged