Clusters overview info
kyma-project/busola pull request #1235
Opened 2022-04-08 10:40 UTC by grego952

**Description**

Changes proposed in this pull request:

- Add info in the **Connect cluster** view that a user can also browse the computer in search for the kubeconfig file.

**Related issue(s)**
Resolves #1233

2022-04-08 19:55 UTC, mrCherry97 submitted a review, later dismissed

2022-04-11 06:20 UTC, akucharska approved these changes

2022-04-11 06:20 UTC, akucharska commented on core/src/i18n/en.yaml
> +    drag-file: Drag your file here or click to browse your computer
Maybe something like: `Choose a file or drag it here` or `Drag your file here or click to upload`

2022-04-11 06:22 UTC, akucharska requested changes
See above

2022-04-11 06:48 UTC, grego952 commented
/retest

2022-04-11 06:54 UTC, grego952 commented
/retest

2022-04-11 07:08 UTC, majakurcius approved these changes

2022-04-11 07:10 UTC, dariadomagala commented
/test all

2022-04-11 07:16 UTC, akucharska approved these changes

2022-04-11 07:23 UTC, akucharska commented
/retest

2022-04-11 07:36 UTC, grego952 commented
/test all

2022-04-11 07:59 UTC, grego952 commented
/retest

2022-04-11 09:16 UTC, merged