Service discovery
kyma-project/busola pull request #1258
Opened 2022-04-19 08:45 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-04-26 10:24 UTC, Wawrzyn321 commented
We'll wait for https://github.com/kyma-project/busola/issues/700 and reopen this again. We left some todos, instructions and comments in the code, so work can be easily resumed.

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +The document explains the usage of feature flags in Busola, as well as lists and describes all the feature flags that are available in Kyma Dashboard and provides their configuration examples:
```suggestion
The document explains the usage of feature flags in Busola, lists and describes all the available feature flags, and provides their configuration examples:
```
Maybe we can shorten the intro like above?

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +Features in Busola initialisation is based on `stage` property, which can take one of the values listed here:
```suggestion
Initialisation of the Busola features is based on the `stage` property, which can take one of the following values:
```

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +- `PRIMARY` - the feature will be resolved while the app bootstraps. Features that should be immediately visible should be set as `PRIMARY` (e.g. main navigation structure).
```suggestion
- `PRIMARY` - the feature is resolved while the application bootstraps. Features that should be immediately visible must be set as `PRIMARY` (for example, main navigation structure).
```

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +- `SECONDARY` - the feature will be resolved after the app is ready, it should be used for non-critical features (e.g. additional navigation nodes).
```suggestion
- `SECONDARY` - the feature is resolved after the application is ready, it must be used for non-critical features (for example, additional navigation nodes).
```

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +- \<other value> - the feature will be loaded only on-demand, most often by the iframe. Use the `useFeature` hook to request usage of such feature.
```suggestion
- \<other value> - the feature is loaded only on-demand, most often by the iframe. Use the `useFeature` hook to request usage of such feature.
```

2022-05-11 09:52 UTC, grego952 commented on docs/features.md
> +Note that some features need to be run before the app starts the bootstrap process (e.g. SSO_LOGIN), so they are out of normal feature flow.
```suggestion
Note that some features must be run before the application starts the bootstrap process (for example, SSO_LOGIN), so they are out of the normal feature flow.
```

2022-05-11 10:12 UTC, Wawrzyn321 commented
/retest

2022-05-11 13:46 UTC, Wawrzyn321 commented
/test all

2022-05-12 08:52 UTC, Wawrzyn321 commented
/retest

2022-05-12 19:45 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s-cluster

2022-05-16 07:10 UTC, qbalukom requested changes

2022-05-16 07:10 UTC, qbalukom commented on core/src/luigi-config/feature-checks.js
> +export function apiGroup(group, refreshIntervalMs = 5 * 60 * 1000) {
maybe go with named parameters instead? to keep it consistent with `service()`?

2022-05-16 08:26 UTC, Wawrzyn321 commented on core/src/luigi-config/cluster-management/cluster-management.js
> +  if (cluster?.config.requiresCA === undefined) {
I heard about it, but is it still possible in modern browsers? 👀

2022-05-16 08:29 UTC, Wawrzyn321 commented on core/src/luigi-config/cluster-management/cluster-management.js
> +  if (cluster?.config.requiresCA === undefined) {
Woah, it is actually possible, but only in IIFE (https://stackoverflow.com/a/8783528/9462061).
It doesn't work in browser console though
<img width="177" alt="image" src="https://user-images.githubusercontent.com/10504661/168551402-bb2048b1-4b02-4d89-bd1a-6139b8f35af3.png">

I'll edit the code anyway.

2022-05-17 11:57 UTC, Wawrzyn321 commented
/retest

2022-05-19 05:40 UTC, qbalukom approved these changes

2022-05-19 06:15 UTC, grego952 commented on docs/features.md
> +- \<other value> - the feature is loaded only on-demand, most often by the iframe. Use the `useFeature` hook to request usage of such feature.
```suggestion
- `{other_value} - the feature is loaded only on-demand, most often by the iframe. Use the `useFeature` hook to request usage of such feature.
```

2022-05-19 06:34 UTC, grego952 approved these changes

2022-05-19 06:45 UTC, qbalukom approved these changes

2022-05-19 06:54 UTC, merged