Fix automatically adding null to yaml editor
kyma-project/busola pull request #1307
Opened 2022-05-09 06:03 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- Fix automatically adding null to yaml editor when typing
- ...
- ...

**Related issue(s)**

Resolves #1288

2022-05-09 07:48 UTC, mrCherry97 requested changes
Doesn't work in Adding Cluster wizard
![image](https://user-images.githubusercontent.com/46759954/167364373-2dec4d89-5649-4cd1-92ff-e02b82eb5c23.png)

2022-05-09 13:03 UTC, mrCherry97 commented on core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
> +      console.log(message);
Maybe a better option is `console.error` ?

2022-05-09 15:06 UTC, wchrapka submitted a review, later dismissed

2022-05-10 05:57 UTC, mrCherry97 approved these changes

2022-05-10 06:30 UTC, wchrapka approved these changes

2022-05-10 06:31 UTC, merged