Test deployments
kyma-project/busola pull request #138
Opened 2021-05-07 13:05 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-05-10 06:00 UTC, Sawthis approved these changes

2021-05-10 06:14 UTC, parostatkiem requested changes

2021-05-10 06:14 UTC, parostatkiem commented on tests/tests/busola-create-a-deployment.spec.js
> +      .click({ force: true });
Is there any reason you use `force` here and below?

2021-05-10 06:14 UTC, parostatkiem commented on tests/tests/busola-create-a-deployment.spec.js
> +      .wait(2000);
You could use `get` or `find` below instead. Cypress will retry looking for the desired element.

2021-05-10 06:14 UTC, parostatkiem commented on tests/cypress.json
> +  "pageLoadTimeout": 10000,
I think we should adjust all the timeouts to our *expectations* to also test if the performance of Busola isn't below the expected threshold. A page loading for 9.5s isn't a success, don't you think?

2021-05-10 06:32 UTC, Sawthis requested changes
Please look on Jan's comments.

2021-05-11 05:21 UTC, Sawthis commented on tests/tests/busola-create-a-deployment.spec.js
> +    cy.visit(ADDRESS)
You need to adjust login flow. Example is here: https://github.com/kyma-project/busola/blob/main/tests/tests/busola-smoke-tests.spec.js#L18

2021-05-11 09:30 UTC, Sawthis requested changes

2021-05-11 10:01 UTC, merged