Logpipelines ext
kyma-project/busola pull request #1430
Opened 2022-06-10 13:21 UTC by wchrapka

**Description**

Add components for LogPipelines

**Related issue(s)**
Resolves #1347

2022-06-13 17:29 UTC, wchrapka commented
/test pre-busola-smoke-test-docker

2022-06-13 17:33 UTC, wchrapka commented
/test pre-busola-integration-test-k3s-cluster
/test pre-busola-integration-test-k3s-namespace

2022-06-15 09:06 UTC, Wawrzyn321 requested changes

2022-06-15 09:06 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
> +  const { data, loading } = useGetList()(url);
I believe it would be good to add error handling. We could pass the `error` from `useGetList` to `ExternalResourceRef` and display it there.

2022-06-15 09:28 UTC, Wawrzyn321 requested changes
I believe the `secretRefs` generation is wrong:
![image](https://user-images.githubusercontent.com/10504661/173794253-72ae3d7c-4486-4c6c-ae79-41acda609c09.png)

2022-06-21 08:34 UTC, Wawrzyn321 approved these changes

2022-06-21 09:46 UTC, Wawrzyn321 approved these changes

2022-06-21 11:01 UTC, Wawrzyn321 commented
/test pre-busola-smoke-test-docker

2022-06-21 13:10 UTC, grego952 commented on docs/extensibility/display-widgets.md
> +CodeViewer widgets display values using a read-only code editor. The editor will autodetect the language.
```suggestion
CodeViewer widgets display values using a read-only code editor. The editor autodetects the language.
```

2022-06-21 13:19 UTC, grego952 commented on docs/extensibility/form-widgets.md
> +CodeEditor widgets render a versatile code editor, that can be used to edit any variable. Editor's default language is JSON.
```suggestion
CodeEditor widgets render a versatile code editor that can be used to edit any variable. The editor's default language is JSON.
```

2022-06-21 13:20 UTC, grego952 commented on docs/extensibility/display-widgets.md
> +### ResourceRef
```suggestion
### ResourceRefs
```

2022-06-21 13:21 UTC, grego952 commented on docs/extensibility/form-widgets.md
> +ResourceRefs widgets render the lists of dropdowns to select the associated resources' names and namespaces. The corresponding specification object must be an array of objects `{name: 'foo', namespac
```suggestion
ResourceRefs widgets render the lists of dropdowns to select the associated resources' names and Namespaces. The corresponding specification object must be an array of objects `{name: 'foo', namespace: 'bar'}`.
```

2022-06-21 13:35 UTC, grego952 commented on docs/extensibility/display-widgets.md
> +Additionally define the kind of the linked resources by passing resource Kubernetes `kind`.
```suggestion
Additionally, you must define the kind of the linked resources by passing the Kubernetes resource `kind` (for example, `Secret`, `ConfigMap`).
```

2022-06-21 13:38 UTC, grego952 approved these changes

2022-06-21 14:16 UTC, Wawrzyn321 approved these changes

2022-06-21 14:21 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-06-21 14:25 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-06-21 14:29 UTC, merged