Expose function test
kyma-project/busola pull request #150
Opened 2021-05-17 06:06 UTC by parostatkiem

**Description**
The test was based on [this](https://kyma-project.io/docs/main/root/getting-started#getting-started-expose-the-function) guide. The _in-memory-cache_ part was skipped on purpose.
Suggested changes for the future: 
Create a namespace once per all test suites, create a function afterwards. Perform all other tests and leave the _expose the function_ part for the end. This will save up a lot of time waiting for the function to be ready.

Changes proposed in this pull request:

- get the Function code dynamically from the Guide 
- create an API Rule for the function 
- check if the generated `host` is valid
- make a request to the `host` and check the response

**Related issue(s)**

2021-05-17 06:52 UTC, parostatkiem commented
/retest

2021-05-17 07:00 UTC, parostatkiem commented
/test pre-busola-ui-test

2021-05-18 11:16 UTC, parostatkiem commented
/test pre-busola-ui-test

2021-05-19 08:08 UTC, parostatkiem commented
/test pre-busola-ui-test

2021-05-19 08:16 UTC, Sawthis requested changes

2021-05-19 08:16 UTC, Sawthis commented on resources/web/deployment.yaml
> +          image: eu.gcr.io/kyma-project/busola-core:PR-136
```suggestion
          image: eu.gcr.io/kyma-project/busola-core:PR-144
```

2021-05-19 08:16 UTC, Sawthis commented on tests/tests/busola-create-a-deployment.spec.js
> +    // console.log(cy.url());
do we need this commented code?

2021-05-19 08:17 UTC, Sawthis commented
/retest

2021-05-19 08:31 UTC, parostatkiem commented
/test pre-busola-ui-test

2021-05-19 08:38 UTC, Sawthis approved these changes

2021-05-19 08:49 UTC, akucharska approved these changes

2021-05-19 08:55 UTC, klaudiagrz approved these changes

2021-05-19 08:56 UTC, merged