Add widget that display joined array entries
kyma-project/busola pull request #1529
Opened 2022-06-30 13:54 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Add widget that display joined array entries

**Related issue(s)**

2022-07-01 06:16 UTC, qbalukom requested changes

2022-07-01 06:16 UTC, qbalukom commented on core-ui/src/components/Extensibility/components/Widget.js
> +  return Array.isArray(childValue) &&
Shouldn't this be solved by simply assigning `JoinedArray.array = true`?

2022-07-01 07:28 UTC, majakurcius commented on core/src/i18n/en.yaml
> +      not-an-array: Wrong data format. Values sgould be an array.
```suggestion
      not-an-array: Wrong data format. Values should be an array.
```

2022-07-01 07:28 UTC, majakurcius commented on docs/extensibility/display-widgets.md
> +- **separator** - a string by which the elements of the array will be separated by. The default value is a comma `,`
```suggestion
- **separator** - a string by which the elements of the array will be separated by. The default value is a comma `,`.
```

2022-07-01 07:55 UTC, majakurcius approved these changes

2022-07-01 08:39 UTC, qbalukom commented
I'd also suggest including a more meaningful example screenshot - with actual words instead of single letters.

2022-07-01 10:33 UTC, akucharska commented
/retest

2022-07-01 11:19 UTC, majakurcius approved these changes

2022-07-01 13:35 UTC, qbalukom submitted a review, later dismissed

2022-07-05 07:44 UTC, qbalukom approved these changes

2022-07-05 07:53 UTC, majakurcius approved these changes

2022-07-05 08:30 UTC, akucharska commented
/retest

2022-07-05 08:49 UTC, merged