Badge highlights
kyma-project/busola pull request #1579
Opened 2022-07-12 06:23 UTC by qbalukom

2022-07-12 06:43 UTC, qbalukom commented
/retest

2022-07-12 07:30 UTC, Wawrzyn321 requested changes
Also, would be nice to have some tests just for the logic in our `Badge` wrapper.

2022-07-13 07:21 UTC, qbalukom commented on core-ui/src/components/Extensibility/components/Badge.js
> +        return jsonata(rule).evaluate({ value });
makes sense

2022-07-14 06:16 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components/Badge.js
> +          console.warn(`invalid rule: ${rule}`);
```suggestion
          console.warn(`invalid rule: ${rule}`, e);
```

2022-07-14 06:16 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components/Badge.js
> +          return jsonata(rule).evaluate({ value });
We use `data` while passing stuff to jsonata, let's be consistent.
```suggestion
          return jsonata(rule).evaluate({ data: value });
```

2022-07-14 06:17 UTC, Wawrzyn321 commented on docs/extensibility/display-widgets.md
> +    "negative": "value < 0"
Same as before
```suggestion
    "negative": "data < 0"
```

2022-07-14 06:31 UTC, Wawrzyn321 approved these changes

2022-07-14 06:44 UTC, Wawrzyn321 commented
/test pre-busola-smoke-test-docker

2022-07-14 08:11 UTC, grego952 commented on docs/extensibility/display-widgets.md
> +- **highlights** - an optional map of highlight rules. Key refers to type of highlight, while the rule can just be a plain array of values or a string containing a jsonata rule. Allowed keys are `inf
```suggestion
- **highlights** - an optional map of highlight rules. Key refers to the type of highlight, while the rule can just be a plain array of values or a string containing a jsonata rule. Allowed keys are `informative` `positive`, `negative` and `critical`.
```

2022-07-14 08:58 UTC, merged