Extensibility form reorder
kyma-project/busola pull request #1612
Opened 2022-07-18 05:59 UTC by qbalukom

**Description**

Changes proposed in this pull request:

- improve extensibility forms to allow reordering and more structured forms

2022-07-20 06:00 UTC, dariadomagala requested changes
I don't see all values I have in my configuration

What I see
<img width="1050" alt="Screen Shot 2022-07-20 at 07 57 38" src="https://user-images.githubusercontent.com/40663133/179907755-c76778df-3b5c-4f59-8742-c2fbf9b7cb51.png">

What's in my config 
```
    {
        "path": "spec.ports[]",
        "simple": true,
        "children": [
          {
            "path": "name",
            "simple": true
          },
          {
            "path": "protocol",
            "simple": true
          },
          {
            "path": "port",
            "simple": true
          },
          {
            "path": "targetPort",
            "simple": true
          }
        ]
      }
```

What's in the resource, so we know this entry exists:
```
spec:
  ports:
    - name: dd3
      protocol: TCP
      port: 5333
      targetPort: 5333
```

2022-07-20 06:47 UTC, qbalukom commented on docs/extensibility/resources.md
> +- **children** - child widgets used for grouping. Child paths are relative to it's parent.
no, because it's not required

2022-07-21 09:29 UTC, wchrapka commented
This spec works on main, but doesn't on this PR:

```
  "form": [
      {
        "path": "spec.aorb"
      },
      { "path": "spec.a" },
      { "path": "spec.b" }
    ],
(...schema:)
  "spec": {
          "description": "LogPipelineSpec defines the desired state of LogPipeline",
          "type": "object",
          "if": {
            "properties": { "aorb": { "const": "a" } }
          },
          "then": {
            "properties": { "a": { "type": "string" } }
          },
          "else": {
            "properties": { "b": { "type": "integer" } }
          },
          "properties": {
            "aorb": {
              "type": "string",
              "enum": ["a", "b"],
              "default": "b"
            },
            "enableUnsupportedPlugins": {
              "type": "boolean"
            },

2022-07-25 06:37 UTC, qbalukom commented
/retest

2022-07-25 09:28 UTC, dariadomagala approved these changes

2022-07-25 09:52 UTC, grego952 commented on docs/extensibility/resources.md
> +- **children** - child widgets used for grouping. Child paths are relative to it's parent.
```suggestion
- **children** - child widgets used for grouping. Child paths are relative to its parent.
```

2022-07-25 09:55 UTC, dariadomagala approved these changes

2022-07-25 09:55 UTC, grego952 approved these changes

2022-07-25 10:18 UTC, merged