move resource to separated object in schema form
kyma-project/busola pull request #1720
Opened 2022-08-08 12:53 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
Closes #1702

2022-08-08 12:59 UTC, mrCherry97 commented
/test all

2022-08-08 13:41 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-08-09 13:31 UTC, akucharska requested changes

2022-08-10 07:42 UTC, mrCherry97 commented on docs/extensibility/form-widgets.md
> +  - **version** - _[required]_ API version used for all requests.
There wasn't `scope` and `namespace` before, so I think no

2022-08-10 07:46 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
> +    schema.get('resource') || {};
Nope, we don't need to do that before the `beta` tag.

2022-08-10 07:52 UTC, akucharska approved these changes

2022-08-10 07:55 UTC, grego952 approved these changes

2022-08-10 09:08 UTC, mrCherry97 commented
/retest

2022-08-10 09:23 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-08-10 11:11 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-08-10 11:20 UTC, merged