Jsonata sources
kyma-project/busola pull request #1727
Opened 2022-08-10 08:47 UTC by qbalukom

Introduce `source` instead of `name` and `formula` for display widgets.
Unify data sources for all widgets.

2022-08-12 10:46 UTC, dariadomagala requested changes

2022-08-12 10:46 UTC, dariadomagala commented on core/src/luigi-config/customResources.js
> +export async function getSchemas() {
Can we rename it? For me, the name suggests that we're taking all the CRDs schemas, while we're taking our own extensibility schemas

2022-08-12 10:46 UTC, dariadomagala commented on docs/extensibility/display-widgets.md
> +  "children": [
what about adjusting the examples?

2022-08-12 10:46 UTC, dariadomagala commented on core-ui/src/components/Extensibility/ExtensibilityDetails.js
> +    throwConfigError(t('extensibility.errors'), { error: ajv.errors });
1. `t` here comes from extensibility translations, not our busola ones so it won't work
2. there's no `extensibility.errors` in our translations, you can use `extensibility.error` (without s) instead, but that will only double the same error. Please use something more descriptive.

2022-08-17 09:26 UTC, dariadomagala requested changes
1. Translations are missing now:
<img width="1098" alt="Screen Shot 2022-08-17 at 11 15 59" src="https://user-images.githubusercontent.com/40663133/185083043-f673d4c2-3f7c-41f8-a2cd-7488160af10d.png">
or 
<img width="237" alt="Screen Shot 2022-08-17 at 11 25 27" src="https://user-images.githubusercontent.com/40663133/185084383-9c151582-21a6-4605-a1bd-054ad07f5e17.png">

2. I've chosen a pizza's secret in the form, but it's not visible in the details
<img width="1367" alt="Screen Shot 2022-08-17 at 11 25 53" src="https://user-images.githubusercontent.com/40663133/185084447-c6c588ef-33c3-4e75-8718-917fe4d03cd4.png">

2022-08-18 06:09 UTC, dariadomagala commented on core-ui/src/components/Extensibility/helpers.js
> +    // const path = storeKeys
please remove unused code

2022-08-18 09:18 UTC, dariadomagala commented
/retest

2022-08-18 09:50 UTC, dariadomagala approved these changes

2022-08-18 10:07 UTC, grego952 commented on docs/extensibility/resources.md
> +Data sources are provided in all [JSONata](https://docs.jsonata.org/overview.html) formulas as functions to call.For example, `{ "source": $myRelatedResource().metadata.labels }` returns the `metadat
```suggestion
Data sources are provided in all [JSONata](https://docs.jsonata.org/overview.html) formulas as functions to call. For example, `{ "source": $myRelatedResource().metadata.labels }` returns the `metadata.labels` of the related resource.
```

2022-08-18 10:07 UTC, grego952 commented on docs/extensibility/resources.md
> +This optional section contains all available languages formatted for [i18next](https://www.i18next.com/) either as YAML or JSON, based on their paths. When a name is provided for a widget that value
```suggestion
This optional section contains all available languages formatted for [i18next](https://www.i18next.com/) either as YAML or JSON, based on their paths. When a name is provided for a widget, that value can be used as the key, and the value is the translation for a specific language.
```

2022-08-18 10:07 UTC, grego952 commented on docs/extensibility/resources.md
> +In addition, if no name is provided, form widgets will automatically try to fetch a translation based on it's **path** attribute, and if that fails, they will use a prettified version of it's last pa
```suggestion
In addition, if no name is provided, form widgets automatically try to fetch a translation based on their **path** attribute, and if that fails, they use a prettified version of the last path item as their name (for example `spec.itemDescription` is prettified to "Item Description"), and by extension as a potential translation key.
```

2022-08-18 10:13 UTC, grego952 approved these changes

2022-08-18 10:27 UTC, qbalukom commented
/retest

2022-08-18 10:43 UTC, qbalukom commented
/retest

2022-08-18 11:03 UTC, dariadomagala approved these changes

2022-08-18 11:05 UTC, grego952 approved these changes

2022-08-18 11:13 UTC, merged