WIP: Add more ext tests
kyma-project/busola pull request #1769
Opened 2022-08-22 06:27 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-08-23 06:07 UTC, dariadomagala commented
/retest

2022-08-23 06:16 UTC, dariadomagala commented
/retest

2022-08-23 11:02 UTC, mrCherry97 commented on tests/cypress.json
> +    "cluster/test-pizzas.spec.js",
I think you can remove that

2022-08-23 11:19 UTC, mrCherry97 requested changes
after changing file organization there are problems with file path
<img width="653" alt="image" src="https://user-images.githubusercontent.com/46759954/186145143-9c8950f6-9ed4-4d4e-8699-8b6f1d166f78.png">

2022-08-23 12:08 UTC, dariadomagala commented
/retest

2022-08-23 12:39 UTC, mrCherry97 submitted a review, later dismissed

2022-08-23 12:57 UTC, grego952 commented on examples/services/README.md
> +The `services` example showcases the Busola's extensibility feature with the native Kubernetes resource.
```suggestion
The `services` example showcases the Busola's extensibility feature with the Kubernetes Service resource.
```

2022-08-23 12:57 UTC, grego952 commented on examples/services/README.md
> +The `configuration.yaml` file consists of a ConfigMap that store the information about the extensibility configuration.
```suggestion
The `configuration.yaml` file consists of a ConfigMap that stores the information about the extensibility configuration.
```

2022-08-23 13:03 UTC, grego952 approved these changes

2022-08-24 08:11 UTC, akucharska approved these changes

2022-08-24 08:13 UTC, merged