Kubeconfig context chooser, UI tests
kyma-project/busola pull request #180
Opened 2021-05-31 13:35 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- Refactor kk upload, add context chooser
  - To create kubeconfig with multiple contexts:
```
export KUBECONFIG=<path_to_kk_1>:<path_to_kk_2>...<path_to_kk_n>, n ∈ ℕ
kc cluster view --flatten > kubeconfig--combined.yaml
```
- Add UI tests for
   - 

**Related issue(s)**

2021-05-31 15:52 UTC, Wawrzyn321 commented
/test pre-busola-ui-test

2021-06-01 12:10 UTC, Wawrzyn321 commented
/test pre-busola-ui-test

2021-06-02 06:22 UTC, dariadomagala requested changes
1. Check this flow:
* Add a Kubeconfig file
* Switch tab to `paste`
* Go pack to `upload` tab
* My uploaded file is there yet, the button is disabled. Adding the file again doesn't help
The same thing happens if I start with the `paste` tab

2. We don't have enough data here to show the context dropdown and inputs like issuer etc. 
<img width="478" alt="Screen Shot 2021-06-02 at 08 10 16" src="https://user-images.githubusercontent.com/40663133/120432333-145d0900-c37a-11eb-9796-cf9b31113bec.png">

3. 
<img width="360" alt="Screen Shot 2021-06-02 at 08 14 43" src="https://user-images.githubusercontent.com/40663133/120432734-a107c700-c37a-11eb-8a52-6f796b895efa.png">
Blank page with the error in the console appeared after I uploaded an invalid kubeconfig

4. If I apply combined kubeconfig using init params, I get only the first context, no option to choose which one I'd want to use

2021-06-02 06:24 UTC, Sawthis requested changes

2021-06-02 06:24 UTC, Sawthis commented on tests/tests/invalid-kubeconfig.spec.js
> +      .getIframeBody()
It should be separate chain cy.getIframeBoddy()...

2021-06-02 06:24 UTC, Sawthis commented on tests/tests/invalid-kubeconfig.spec.js
> +      .get('[data-testid=addcluster]')
It should be separate chain

2021-06-02 06:24 UTC, Sawthis commented on tests/tests/login-enkode.spec.js
> +  it('Only params from enkode, upload kubeconfig manually', () => {
```suggestion
  it('Only params from enkode without kubeconfig', () => {
```

2021-06-02 06:24 UTC, Sawthis commented on tests/tests/login-enkode.spec.js
> +  it('Login with no token in kubeconfig', () => {
```suggestion
  it('Login without token in kubeconfig', () => {
```

2021-06-02 10:01 UTC, Sawthis approved these changes

2021-06-02 15:01 UTC, Sawthis submitted a review, later dismissed

2021-06-07 05:28 UTC, Sawthis approved these changes

2021-06-07 06:35 UTC, dariadomagala reviewed
After choosing a context it jums back to the `apply kubeconfig` view for 1-2sec, could we avoid it?

2021-06-07 07:55 UTC, dariadomagala approved these changes

2021-06-07 07:58 UTC, merged