Reverse sidecar
kyma-project/busola pull request #1816
Opened 2022-09-05 08:35 UTC by wchrapka

**Description**

Changes proposed in this pull request:

- always include the sidecar injection label enabled/disabled
- remove istio switch from jobs
- add istio switch to deployments

**Related issue(s)**
Resolves #1689

2022-09-05 13:03 UTC, qbalukom requested changes

2022-09-05 13:42 UTC, wchrapka commented on core-ui/src/resources/Namespaces/NamespaceCreate.js
>  const ISTIO_INJECTION_LABEL = 'istio-injection';
This is a standard practice for defining constants that are dependent on some external sources. We use it `run-prepare-functions.spec`

2022-09-05 14:31 UTC, wchrapka commented on core-ui/src/resources/Deployments/DeploymentCreate.js
> +        advanced={!isIstioFeatureOn}
Checked and changed - the component is hidden when Istio is off

2022-09-06 06:30 UTC, qbalukom requested changes

2022-09-06 06:30 UTC, qbalukom commented on core-ui/src/resources/Deployments/DeploymentCreate.js
> +          simple
is it supposed to be simple-only then?
i believe this flag should be removed completely

2022-09-06 06:40 UTC, qbalukom approved these changes

2022-09-06 08:00 UTC, wchrapka commented
/retest

2022-09-06 08:21 UTC, grego952 approved these changes

2022-09-06 08:52 UTC, wchrapka commented
/test pre-busola-integration-test-k3s-namespace

2022-09-06 09:08 UTC, merged