Ext function form
kyma-project/busola pull request #1842
Opened 2022-09-14 08:03 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-09-16 07:43 UTC, Lyczeq requested changes

2022-09-19 07:01 UTC, Wawrzyn321 commented
I'll also add Env variables to the form.

2022-09-21 08:54 UTC, mrCherry97 commented
/pony

2022-09-21 21:00 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components-form/NumberRenderer.js
> +    ['min', 'max'].map(prop => [prop, schema.get(prop)]),
[`633e07a` (#1842)](https://github.com/kyma-project/busola/pull/1842/commits/633e07ac0a6540ce292ee0ea3e92e415cec19f17)

2022-09-21 21:27 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/helpers/index.js
> +    tryTranslate: path => (exists(path) ? t(path) : ''),
I rolled back those changes, they aren't needed anymore.

2022-09-22 07:05 UTC, Wawrzyn321 commented
/retest

2022-09-22 07:56 UTC, Wawrzyn321 commented
/retest

2022-09-22 08:08 UTC, grego952 commented on docs/extensibility/form-section.md
> +Any parameters that are not handled by the widget are added to the schema directly, so it's possible to add or override existing values. For example, add an **enum** parameter to provide selectable v
```suggestion
Any parameters that are not handled by the widget are added to the schema directly, so it's possible to add or override existing values. For example, add an **enum** parameter to provide selectable values in a field or specify additional parameters to improve the schema validation, for example, `min` and `max` attributes for numeric inputs to enable HTML validation.
```

2022-09-22 08:08 UTC, grego952 commented on docs/extensibility/form-section.md
> +- **language** - a jsonata expression resolving the desired language. It has access to `$root` variable, containing the entire resource.
```suggestion
- **language** - a JSONata expression resolving the desired language. It has access to the `$root` variable, containing the entire resource.
```

2022-09-22 08:08 UTC, grego952 commented on docs/extensibility/form-section.md
> +  "description": "Data that will be passed on to the application.",
```suggestion
  "description": "Data is passed on to the application.",
```

2022-09-22 08:08 UTC, grego952 commented on docs/extensibility/form-section.md
> +> NOTE: Remember to put both single and double quotes if you want to use plain language (e.g. "'YAML'"). Specyfing just double quotes ("YAML") makes Busola try to access nonexistent `YAML` variable,
```suggestion
> NOTE: Remember to put both single and double quotes if you want to use plain language (for example, "'YAML'"). Specifying just double quotes ("YAML") makes Busola try to access a nonexistent `YAML` variable, resulting in the language being `undefined`.
```

2022-09-22 08:08 UTC, grego952 commented on docs/extensibility/form-section.md
> +- **columns** - number of columns the content should be rendered in. Defaults to 1.
```suggestion
- **columns** - number of columns the content is rendered in. Defaults to 1.
```

2022-09-22 08:48 UTC, Lyczeq submitted a review, later dismissed

2022-09-22 08:52 UTC, grego952 submitted a review, later dismissed

2022-09-22 09:31 UTC, Wawrzyn321 commented
/retest

2022-09-22 10:28 UTC, Wawrzyn321 commented
/retest

2022-09-22 10:32 UTC, Lyczeq approved these changes

2022-09-22 11:06 UTC, grego952 approved these changes

2022-09-22 11:34 UTC, merged