dynamic values wip
kyma-project/busola pull request #1850
Opened 2022-09-15 09:39 UTC by qbalukom

2022-09-19 08:00 UTC, Wawrzyn321 commented on core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
> +      title={tFromStoreKeys(storeKeys, schema)}
Please remove it from translations.

2022-09-19 11:54 UTC, Wawrzyn321 submitted a review, later dismissed

2022-09-19 12:15 UTC, qbalukom commented
/retest

2022-09-19 12:21 UTC, grego952 commented on docs/extensibility/form-section.md
> +- **defaultValue** - default value to use for the variable when opening the form.
```suggestion
- **defaultValue** - default value used for the variable when opening the form.
```

2022-09-19 12:30 UTC, grego952 approved these changes

2022-09-19 14:13 UTC, Wawrzyn321 requested changes
It looks like dynamic/default values don't work for items nested inside arrays:
```json
 "children": [
    "path": "[]",
      "children": [
		{
			"var": ...
```

You can check it on `/cluster/shoot--hasselhoff--kmain/namespaces/default/qqqs` - if you use YAML:
```yaml
apiVersion: busola.example.com/v1
kind: Qqq
spec:
  list-items:
    - description: 'a'
      name: 'b'
```

and get back to "Simple" the `description` is removed, while it should be left alone, according to `dynamicValue: "$boolean($item.description)"`.

2022-09-21 13:07 UTC, Wawrzyn321 approved these changes

2022-09-21 13:09 UTC, Wawrzyn321 commented
/retest

2022-09-21 13:26 UTC, merged