WIP: Details functions config
kyma-project/busola pull request #1858
Opened 2022-09-19 11:48 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-09-20 06:02 UTC, dariadomagala commented
/retest

2022-09-20 11:25 UTC, dariadomagala commented
/retest

2022-09-20 13:34 UTC, akucharska requested changes

2022-09-20 13:34 UTC, akucharska commented on examples/resources/serverless/functions.yaml
> +                  "widget": "ResourceList",
After the creation of the Subscription from the Function details view, the user is redirected to subscription details. Instead, it should stay on the function detail page.

2022-09-20 13:34 UTC, akucharska commented on docs/extensibility/display-section.md
> +  - [Tabs](#tabs)
Lets keep alphabetical order here

2022-09-20 13:34 UTC, akucharska commented on docs/extensibility/display-section.md
> +### Tabs
Move it to the end of the section (after `Table`) to keep alphabetical order.

2022-09-21 08:39 UTC, dariadomagala commented on examples/resources/serverless/functions.yaml
> +                      "source": "$item.owners"
no, it was taken from the owners https://github.com/kyma-project/busola/blob/main/core-ui/src/components/Functions/FunctionDetails/Tabs/Code/FunctionVariables/FunctionVariables.js#L142

2022-09-22 06:17 UTC, akucharska commented on examples/resources/serverless/functions.yaml
> +                      "source": "$item.owners"
Yes but the `variable` is not part of the function. It is prepared from `customVariables` and `customValueFromVariables`:
```
const entries = [
    ...validateVariables(customVariables),
    ...validateVariables(customValueFromVariables),
  ];
```
those are prepared from `secrets`, `configmaps`, and `function.spec.env` data:
```
const { customVariables, customValueFromVariables } = serializeVariables({
    functionVariables: func?.spec?.env,
    secrets: secrets,
    configmaps: configmaps,
  });
```

Here is the function that prepares variables and the second which takes ownerReferences
https://github.com/kyma-project/busola/blob/main/core-ui/src/components/Functions/helpers/functionVariables/serializeVariables.js#L4
https://github.com/kyma-project/busola/blob/main/core-ui/src/components/Functions/helpers/functionVariables/serializeVariables.js#L65

2022-09-22 07:08 UTC, dariadomagala commented on examples/resources/serverless/functions.yaml
> +                      "source": "$item.owners"
We've decided to remove this field

2022-09-22 07:31 UTC, dariadomagala commented
/retest

2022-09-22 07:51 UTC, grego952 commented on docs/extensibility/display-section.md
> +- **linkText** - a jsonata expression resolving the link text, this property has access to **data** and **root**. To insert dynamic parts of translations, use double quotes `Go to {{data.name}}`.
```suggestion
- **linkText** - a JSONata expression resolving a link text, this property has access to **data** and **root**. To insert dynamic parts of translations, use double quotes `Go to {{data.name}}`.
```

2022-09-22 07:51 UTC, grego952 commented on docs/extensibility/display-section.md
> +- **language** - a jsonata expression resolving the desired language, used for code highlighting. It has access to the `$root` variable, containing the entire resource. The editor supports languages
```suggestion
- **language** - a JSONata expression resolving the desired language, used for code highlighting. It has access to the `$root` variable, containing the entire resource. The editor supports languages handled by [Monaco](https://code.visualstudio.com/docs/languages/overview).
```

2022-09-22 08:03 UTC, grego952 submitted a review, later dismissed

2022-09-22 08:26 UTC, dariadomagala commented
/retest

2022-09-22 09:03 UTC, dariadomagala commented
/retest

2022-09-22 09:11 UTC, dariadomagala commented
/retest

2022-09-22 10:28 UTC, dariadomagala commented
/retest

2022-09-22 11:21 UTC, akucharska approved these changes

2022-09-22 11:53 UTC, dariadomagala commented
/retest

2022-09-22 11:59 UTC, dariadomagala commented
/retest

2022-09-22 14:00 UTC, grego952 approved these changes

2022-09-22 14:02 UTC, merged