Introduce Reset form button
kyma-project/busola pull request #1905
Opened 2022-10-04 07:49 UTC by Lyczeq

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-10-06 13:21 UTC, Lyczeq commented
/retest

2022-10-07 06:44 UTC, Lyczeq commented
/retest

2022-10-10 09:52 UTC, dariadomagala requested changes
I believe that reset button in namespaces should also reset limits and quotas settings

2022-10-12 06:02 UTC, Lyczeq commented
/retest

2022-10-12 06:31 UTC, dariadomagala commented on core-ui/src/resources/Namespaces/NamespaceCreate.js
> +        setMemory(createResourceQuotaTemplate({}));
I believe the 3 functions below are not needed

2022-10-12 06:51 UTC, dariadomagala approved these changes

2022-10-12 06:51 UTC, dariadomagala commented
/retest

2022-10-12 06:54 UTC, grego952 approved these changes

2022-10-12 07:09 UTC, merged