added subscription.yaml and jsonata function for timestamp
kyma-project/busola pull request #1912
Opened 2022-10-06 08:21 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
Closes #1866

2022-10-10 17:03 UTC, mrCherry97 commented
/retest

2022-10-11 12:40 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-10-11 13:05 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-10-11 13:25 UTC, mrCherry97 commented
/retest

2022-10-11 13:34 UTC, mrCherry97 commented
/retest

2022-10-12 06:40 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-10-12 07:27 UTC, Lyczeq requested changes

2022-10-12 07:27 UTC, Lyczeq commented on docs/extensibility/form-section.md
> +       type: exact
Could you add one tab before `property`, please? I believe it should be at the same level as `type` and `value`.

2022-10-12 07:27 UTC, Lyczeq commented on examples/resources/configuration/subscriptions.yaml
> +    app.kubernetes.io/name: subscriptions.eventing.kyma-project.io
Hm, shouldn't `name` and `app.kubernetes.io/name` label be the same? ConfigMap automatically adds that label based on the name. We have a similar approach with other extensibility configurations.

2022-10-12 07:27 UTC, Lyczeq commented on examples/resources/configuration/subscriptions.yaml
> +      required: true
I don't think that `required` flag is needed here. It's automatically set based on the schema.

2022-10-12 07:27 UTC, Lyczeq commented on examples/resources/configuration/subscriptions.yaml
> +          required: true
I don't think that `required` flag is needed here. It's automatically set based on the schema.

2022-10-12 08:56 UTC, grego952 approved these changes

2022-10-12 09:12 UTC, grego952 commented on examples/resources/configuration/subscriptions.yaml
> +      inputInfo.eventType: Event Type structure, 'sap.kyma.custom.{APP}.{EVENT.NAME}.{VERSION}'
```suggestion
      inputInfo.eventType: Event Type structure, 'sap.kyma.custom.{APP}.{NAME}.{VERSION}'
```

2022-10-12 09:14 UTC, grego952 approved these changes

2022-10-12 09:16 UTC, Lyczeq approved these changes

2022-10-12 09:27 UTC, mrCherry97 commented
/retest

2022-10-12 09:42 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-10-12 10:22 UTC, Lyczeq commented
/test pre-busola-integration-test-k3s-namespace

2022-10-12 10:41 UTC, merged