WIP: Align form fields
kyma-project/busola pull request #1947
Opened 2022-10-18 07:51 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-10-18 11:46 UTC, dariadomagala commented
/retest

2022-10-19 11:55 UTC, Wawrzyn321 commented on core-ui/src/shared/components/Select/Select.js
> +      <FdSelect {...props} />{' '}
```suggestion
      <FdSelect {...props} />
```

2022-10-19 11:59 UTC, Wawrzyn321 requested changes
Would you kindly fix the misaligned preferences?
<img width="543" alt="image" src="https://user-images.githubusercontent.com/10504661/196684517-af7f3ef9-8eba-4637-8b30-bd1d91aa7ff2.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/10504661/196684557-bebd4ecc-3627-470b-aa33-2c71b6db0994.png">

2nd one has a too big of a padding.

2022-10-19 13:44 UTC, Wawrzyn321 commented on core-ui/src/shared/ResourceForm/components/CollapsibleSection.scss
> +      // left: 16px;
```suggestion
```
Or just revert entire file.

2022-10-19 13:47 UTC, Wawrzyn321 commented on core-ui/src/shared/ResourceForm/fields/K8sNameField.js
> +            <div className="fd-col fd-col-md--11">
`k8s-name-field` class rule can be removed then.

2022-10-19 13:48 UTC, Wawrzyn321 commented on core-ui/src/shared/ResourceForm/fields/TextArrayInput.scss
> +// .text-array-input__list li {
To remove?

2022-10-20 11:22 UTC, Wawrzyn321 reviewed
Should we align KeyValueFields in BTP stuff?
From:
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/10504661/196935384-a9357096-091b-4f81-8288-094903e3ba4e.png">

into:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/10504661/196935427-12a78d4c-f21f-47c1-821f-1c43c176d5c1.png">

So that they look the same as Labels / Annotations. Removing the `fullWidth` prop on their create forms will do.

2022-10-20 11:24 UTC, Wawrzyn321 commented
Let's keep all change requests here:
![image](https://user-images.githubusercontent.com/10504661/196935794-61fc355f-1bb5-44e7-b86e-829b4ebbf1a8.png)

2022-10-20 11:25 UTC, Wawrzyn321 commented
Also please align the "type" input:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/10504661/196936031-f310fcb1-41e5-4798-a8bf-55fa7520bebf.png">

2022-10-20 11:27 UTC, Wawrzyn321 commented
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/10504661/196936396-dc651c32-afd2-425c-aae6-88987190109f.png">

2022-10-20 11:27 UTC, Wawrzyn321 commented
<img width="906" alt="image" src="https://user-images.githubusercontent.com/10504661/196936476-fe6e7126-2377-4902-ad5b-0cab4cc28950.png">

2022-10-23 08:37 UTC, dariadomagala commented
> Also the "language" option is misplaced in CMs: <img alt="image" width="1156" src="https://user-images.githubusercontent.com/10504661/196935713-1f49f5fe-ced9-46a6-8b90-d90cea24b719.png">

It was always placed like this

2022-10-24 07:35 UTC, dariadomagala commented
/retest

2022-10-26 09:00 UTC, Wawrzyn321 approved these changes

2022-10-26 09:04 UTC, grego952 approved these changes

2022-10-26 09:12 UTC, dariadomagala commented
/retest

2022-10-26 14:21 UTC, Wawrzyn321 approved these changes

2022-10-27 05:46 UTC, dariadomagala commented
/retest

2022-10-27 06:09 UTC, dariadomagala commented
/retest

2022-10-27 06:52 UTC, grego952 approved these changes

2022-10-27 06:53 UTC, merged