remove old implementation of sidecars
kyma-project/busola pull request #1991
Opened 2022-10-27 11:30 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- remove old implementation of Sidecars
- adjust tests to extensibility implementation
- ...

**Related issue(s)**
part of #1964

2022-10-27 12:05 UTC, mrCherry97 commented
/retest

2022-10-27 13:35 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-10-27 22:17 UTC, mrCherry97 commented
/retest

2022-10-28 07:45 UTC, mrCherry97 commented
/retest

2022-10-28 08:04 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-10-28 08:32 UTC, mrCherry97 commented
/retest

2022-10-28 08:57 UTC, mrCherry97 commented
/retest

2022-10-28 10:25 UTC, mrCherry97 commented
/retest

2022-10-28 10:26 UTC, mrCherry97 commented
/retest

2022-10-31 12:26 UTC, mrCherry97 commented
/retest

2022-10-31 13:16 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-10-31 13:33 UTC, mrCherry97 commented
/retest

2022-10-31 14:18 UTC, mrCherry97 commented
/retest

2022-10-31 15:00 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-11-02 08:44 UTC, mrCherry97 commented
/retest

2022-11-02 08:55 UTC, mrCherry97 commented
/retest

2022-11-02 10:38 UTC, mrCherry97 commented
/retest

2022-11-02 10:38 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-11-02 10:44 UTC, mrCherry97 commented
/retest

2022-11-02 11:06 UTC, mrCherry97 commented
/retest

2022-11-02 11:12 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-11-02 11:17 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-11-02 11:23 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-11-02 13:49 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2022-11-02 14:36 UTC, mrCherry97 commented
/test all

2022-11-02 14:37 UTC, mrCherry97 commented
/retest

2022-11-02 15:09 UTC, mrCherry97 commented
/retest

2022-11-02 16:15 UTC, mrCherry97 commented
/retest

2022-11-03 07:11 UTC, mrCherry97 commented
/retest

2022-11-03 12:20 UTC, akucharska requested changes
Remove sidecars from translations

2022-11-03 13:00 UTC, akucharska submitted a review, later dismissed

2022-11-03 13:20 UTC, mrCherry97 commented
/retest

2022-11-03 14:09 UTC, IwonaLanger commented on core-ui/src/components/Extensibility/hooks/useVariables.js
> +// Cypress uses chorme 95 which doesn't support findLastIndex
```suggestion
// Cypress uses Chrome 95 which doesn't support findLastIndex
```

2022-11-03 14:12 UTC, IwonaLanger approved these changes

2022-11-03 14:32 UTC, mrCherry97 commented
/test pre-busola-smoke-test-docker

2022-11-04 06:50 UTC, akucharska commented
/retest

2022-11-04 06:51 UTC, akucharska approved these changes

2022-11-04 06:51 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-11-04 06:59 UTC, akucharska commented
/retest

2022-11-04 07:41 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-11-04 08:01 UTC, merged