Rename console to busola and pamela to backend
kyma-project/busola pull request #2
Opened 2021-03-15 10:32 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- Rename console to busola and pamela to backend

**Related issue(s)**

2021-03-15 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/busola?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/busola?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/busola?pullRequest=2) it.</sub>

2021-03-15 15:15 UTC, Wawrzyn321 commented on components/react/src/components/Search/Readme.md
> +  <h5>Search with `onChange` function (see Developer Busolafor output)</h5>
```suggestion
  <h5>Search with `onChange` function (see Developer Busola for output)</h5>
```

2021-03-15 15:15 UTC, Wawrzyn321 commented on backend/index.js
> +      console.log(`👙 Busola backend 👄 server started @ ${port}!`);
```suggestion
      console.log(`Busola backend server started @ ${port}!`);
```
:(

2021-03-15 15:35 UTC, Wawrzyn321 requested changes
Would you kindly change also `fetchConsoleInitData`?

2021-03-16 07:39 UTC, dariadomagala commented on backend/index.js
> +      console.log(`👙 Busola backend 👄 server started @ ${port}!`);
😢 are you sure?

2021-03-16 11:47 UTC, akucharska commented
/test all

2021-03-16 11:57 UTC, dariadomagala commented
/test all

2021-03-16 12:04 UTC, akucharska commented
/test all

2021-03-16 12:10 UTC, Wawrzyn321 approved these changes

2021-03-16 12:19 UTC, valentinvieriu approved these changes

2021-03-16 12:19 UTC, merged