Readonly name
kyma-project/busola pull request #2011
Opened 2022-11-07 07:19 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Set main name widget in read-only mode when resource is edited
- Fix error with wrong import

**Related issue(s)**

2022-11-07 07:23 UTC, Wawrzyn321 commented
/retest

2022-11-07 09:40 UTC, mrCherry97 submitted a review, later dismissed
If we want to allow user to decide what input can be edited, we need to make it in different way in my opinion.

2022-11-07 09:40 UTC, mrCherry97 commented on core-ui/src/components/Extensibility/components-form/NameRenderer.js
> +      readOnly={editMode}
We don't need `editMode` in schema, if I use `widget: Name` in schema for input, it is disabling input in Create too. 

![image](https://user-images.githubusercontent.com/46759954/200277575-8114c5e5-ef34-4437-8843-94fe8846e4af.png)

We need that only in `ExtensibilityCreate` and `ResourceDetails`, like we had it in "old" implementation.

2022-11-08 09:02 UTC, akucharska commented
/retest

2022-11-08 13:44 UTC, akucharska commented
/retest

2022-11-09 07:40 UTC, dariadomagala requested changes
All examples are in light mode, we should stick to one approach

2022-11-09 12:24 UTC, akucharska commented
/retest

2022-11-09 15:07 UTC, grego952 approved these changes

2022-11-10 09:09 UTC, akucharska commented
/retest

2022-11-10 10:03 UTC, Lyczeq commented
/retest

2022-11-10 10:23 UTC, merged