Extensibility UI - ui-schema version
kyma-project/busola pull request #2023
Opened 2022-11-09 14:33 UTC by qbalukom

2022-11-29 09:33 UTC, mrCherry97 requested changes
- [ ] remove comments,
- [x] Jsonata.js usused `exists`
- [x] path is jsonata in forms
- [ ] in Examples functions data isn't loaded in details
- [ ] ![image](https://user-images.githubusercontent.com/46759954/204494499-45c8f7cc-9454-438d-b59b-79cd4d2d6306.png)

2022-11-29 09:33 UTC, mrCherry97 commented on core-ui/src/components/Extensibility/components-form/MultiType.js
> +    // .set('name', '') // TODO
As we have a talk it should be deleted or make a followup.

2022-11-29 09:33 UTC, mrCherry97 commented on core-ui/src/components/Extensibility/components-form/index.js
> +    // CustomFieldInjector,
To remove

2022-12-05 12:13 UTC, qbalukom commented
/retest

2022-12-05 13:48 UTC, mrCherry97 commented
/retest

2022-12-05 13:54 UTC, mrCherry97 submitted a review, later dismissed

2022-12-05 14:03 UTC, IwonaLanger commented on docs/extensibility/resources.md
> +- **icon** - suffix of an icon name used for the left-hand menu. the default value is `customized`. You can find the list of icons [here](https://sap.github.io/fundamental-react/?path=/docs/component
```suggestion
- **icon** - suffix of an icon name used for the left-hand menu. The default value is `customized`. You can find the list of icons [here](https://sap.github.io/fundamental-react/?path=/docs/component-api-icon--primary#icon-list).
```

2022-12-05 14:06 UTC, mrCherry97 submitted a review, later dismissed

2022-12-05 14:07 UTC, IwonaLanger approved these changes

2022-12-05 14:23 UTC, mrCherry97 commented
/retest

2022-12-05 14:32 UTC, mrCherry97 commented
/test pre-main-busola-governance

2022-12-05 14:45 UTC, IwonaLanger approved these changes

2022-12-05 14:50 UTC, mrCherry97 approved these changes

2022-12-06 07:42 UTC, mrCherry97 commented
/retest

2022-12-06 07:47 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-12-06 09:11 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2022-12-06 12:44 UTC, merged