fix: non-existing Namespace displays details/list
kyma-project/busola pull request #2233
Opened 2022-12-28 15:56 UTC by Lyczeq

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-01-04 10:31 UTC, Lyczeq commented
/retest

2023-01-09 10:23 UTC, akucharska submitted a review, later dismissed

2023-01-09 10:23 UTC, akucharska commented
/retest

2023-01-09 10:57 UTC, mrCherry97 requested changes

2023-01-09 10:57 UTC, mrCherry97 commented on core-ui/public/defaultConfig.yaml
> +      isEnabled: false
We decide with V to enable it by default

2023-01-09 10:57 UTC, mrCherry97 commented
/retest

2023-01-09 11:06 UTC, mrCherry97 commented
/retest

2023-01-09 11:23 UTC, mrCherry97 approved these changes

2023-01-09 11:26 UTC, akucharska approved these changes

2023-01-09 11:28 UTC, IwonaLanger approved these changes

2023-01-09 11:41 UTC, merged