Dnsproviders as extension
kyma-project/busola pull request #2238
Opened 2022-12-29 11:44 UTC by chriskari

**Description**

Changes proposed in this pull request:

- adjusted tests
- removed old codebase

**Related issue(s)**
closes #1956

2022-12-30 11:14 UTC, mrCherry97 commented
/retest

2023-01-04 13:34 UTC, mrCherry97 requested changes
After our changes to testing part of busola and kyma-dashboard, test should be moved to kyma-dashboard and extension should be removed from busola codebase.

2023-01-04 13:34 UTC, mrCherry97 commented on tests/tests/namespace/test-dns-providers.spec.js
> +    //  .click();
This should be removed

2023-01-04 13:34 UTC, mrCherry97 commented
/woof

2023-01-11 11:53 UTC, mrCherry97 requested changes
Remove `test-dns-providers.spec.js` from `cypress.json`

2023-01-12 08:50 UTC, mrCherry97 approved these changes

2023-01-12 09:37 UTC, nataliasitko approved these changes

2023-01-12 09:39 UTC, merged