Move core UI
kyma-project/busola pull request #2250
Opened 2023-01-05 07:27 UTC by qbalukom

2023-01-10 07:14 UTC, qbalukom commented
/retest

2023-01-10 10:20 UTC, qbalukom commented
/retest

2023-01-11 10:13 UTC, mrCherry97 requested changes
Please remove `core` folder too

2023-01-11 10:13 UTC, mrCherry97 commented on package.json
> +  "eslintConfig": {
Please add `    "ignorePatterns": "tests/*",`

2023-01-11 10:17 UTC, mrCherry97 commented on Dockerfile.local
> -COPY --from=builder /app/core-ui/build /app/core-ui
As we have a talk, please open new task as follow-up to change all `core-ui` from images etc

2023-01-11 12:27 UTC, mrCherry97 submitted a review, later dismissed

2023-01-11 13:13 UTC, mrCherry97 approved these changes

2023-01-11 13:30 UTC, IwonaLanger approved these changes

2023-01-11 13:31 UTC, merged