Prettier tests
kyma-project/busola pull request #2251
Opened 2023-01-05 07:34 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-01-09 14:23 UTC, Lyczeq requested changes

2023-01-09 14:23 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +      .should('have.value', 'default name');
I'd propose to change the value of the dynamic input from `default name` to `dynamic name`.

2023-01-09 14:23 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +      // .find('[aria-label="Combobox input arrow"]:visible', { log: false })
If the comment is not necessary, please remove it.

2023-01-09 14:23 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +      .click();
I think there's no need to check whether element exists if you want it to be clicked later.

2023-01-09 14:23 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +  });
I see that `Fixes` template clears the name of the resource. Could you test dynamicValue input to have `unnamed` value? I think it's a good use case.

2023-01-09 14:40 UTC, akucharska commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +
This way we know the navigation node is created properly. And we can not use `cy.goToNamespaceDetails` cause it uses `Cypress.env('NAMESPACE_NAME')`

2023-01-10 08:58 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +
`cy.navigateTo` actually will work, but it's up to you if you want to use it. It's already created and will take less code. Fair point about `cy.goToNamespaceDetails`, forgot about it.

2023-01-10 09:03 UTC, Lyczeq commented on tests/integration/tests/extensibility/ext-test-variables.spec.js
> +      .click();
```suggestion
    cy.get('@form')
      .contains('Choose preset')
      .click();
```

I think it's enough to find the preset dropdown and click it.

2023-01-10 09:41 UTC, Lyczeq approved these changes

2023-01-10 09:59 UTC, merged