add "decode" option to panel
kyma-project/busola pull request #2284
Opened 2023-01-16 11:25 UTC by qbalukom

2023-01-16 12:27 UTC, mrCherry97 requested changes
Code looks fine, I will test it a little bit and make re-review

2023-01-16 12:27 UTC, mrCherry97 commented on src/components/Extensibility/components/Panel.js
> +              //disabled={!secret?.data}
probably it should be uncommented

2023-01-16 14:43 UTC, qbalukom commented on src/components/Extensibility/components/Panel.js
> +              //disabled={!secret?.data}
probably should be removed

2023-01-17 07:07 UTC, mrCherry97 submitted a review, later dismissed

2023-01-17 07:26 UTC, grego952 commented on docs/extensibility/display-section.md
> +- **decodable** - decodes the values of all the children using base64 - has to be used together with the **source** parameter.
```suggestion
- **decodable** - decodes the values of all the children using base64 - must be used together with the **source** parameter.
```

2023-01-17 07:27 UTC, grego952 commented on public/schemas/schema-details.yaml
> +          description: Allow decoding of child values using base64
```suggestion
          description: Allows decoding of child values using base64
```

2023-01-17 08:12 UTC, mrCherry97 approved these changes

2023-01-17 08:25 UTC, mrCherry97 commented
/retest

2023-01-17 08:36 UTC, merged