bump hpa to v2 and adjust non required fields
kyma-project/busola pull request #2293
Opened 2023-01-18 12:17 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-01-18 12:21 UTC, mrCherry97 commented
Everything should work fine, going threw [kubernetes examples of HPA usage](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) everything is fine. Busola is displaying everything properly, etc.

2023-01-19 12:51 UTC, mrCherry97 commented
/retest

2023-01-19 13:24 UTC, mrCherry97 commented
/test pre-busola-lighthouse

2023-01-19 14:03 UTC, mrCherry97 commented
/retest

2023-01-19 14:03 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-cluster

2023-01-19 14:04 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2023-01-19 15:00 UTC, mrCherry97 commented
/retest

2023-01-20 07:47 UTC, mrCherry97 commented
/retest

2023-01-20 08:10 UTC, mrCherry97 commented
/retest

2023-01-20 08:45 UTC, Lyczeq requested changes

2023-01-20 08:45 UTC, Lyczeq commented on src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerDetails.js
> +                value={scaleUp?.selectPolicy ?? EMPTY_TEXT_PLACEHOLDER}
If you check whether `scaleUp` exists, there's no need to use optional chaining in '140 and '145. Error won't be thrown.

2023-01-20 08:45 UTC, Lyczeq commented on src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerDetails.js
> +                value={scaleDown?.selectPolicy ?? EMPTY_TEXT_PLACEHOLDER}
If you check whether `scaleDown` exists, there's no need to use optional chaining in '173 and '179. Error won't be thrown.

2023-01-20 10:48 UTC, Lyczeq approved these changes

2023-01-20 10:51 UTC, grego952 approved these changes

2023-01-20 11:07 UTC, mrCherry97 commented
/retest

2023-01-20 11:18 UTC, merged