removed old codebase of certificates
kyma-project/busola pull request #2296
Opened 2023-01-19 10:25 UTC by chriskari

**Description**

Changes proposed in this pull request:

- removed old codebase, extension and tests

**Related issue(s)**
closes #1958

2023-01-20 14:37 UTC, Lyczeq commented on public/i18n/en.yaml
> -    will-expire: Certificate will expire in {{daysToExpire}} {{daysForm}}.
You deleted some of the important translations there. The component `CertificateDate` still uses them. They're quite related to Secrets, so you can move them right there.

2023-01-23 11:05 UTC, chriskari commented
/retest

2023-01-23 11:06 UTC, chriskari commented
/woof

2023-01-25 09:40 UTC, Lyczeq commented
blocked by https://github.com/kyma-project/busola/pull/2308 and https://github.com/kyma-project/busola/pull/2309

2023-01-25 09:40 UTC, Lyczeq commented
/retest

2023-03-01 09:43 UTC, mrCherry97 requested changes
`src/components/Predefined/Details/Certificate/CertificateRefs.scss` also could be removed, it's not used anywhere

2023-03-01 09:43 UTC, mrCherry97 commented on tests/integration/tests/namespace/test-custom-resources.spec.js
> -    cy.contains('certificates.cert.gardener.cloud').click();
why it's removed?

2023-03-01 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/busola?pullRequest=2296) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/busola?pullRequest=2296) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: Lyczeq<br/>:white_check_mark: chriskari<br/>:x: mrCherry97<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/busola?pullRequest=2296) it.</sub>

2023-03-01 10:28 UTC, mrCherry97 submitted a review, later dismissed

2023-03-01 10:29 UTC, NHingerl approved these changes

2023-03-01 10:35 UTC, mrCherry97 approved these changes

2023-03-01 10:52 UTC, merged