Multi namespace
kyma-project/busola pull request #2354
Opened 2023-02-17 06:45 UTC by qbalukom

- add "all namespaces" option  in namespace dropdown
- display resources from all namespaces when in "all namespaces" mode
- show namespace resources from all namespaces in command palette
- show "all namespaces" option when typing "ns all", "ns -a" or "ns *" in command palette

2023-02-17 08:43 UTC, mrCherry97 requested changes
As we have a talk, we need to catch something like this error 
![image](https://user-images.githubusercontent.com/46759954/219595980-9a7f9e56-6334-4d81-a520-4996ea94ac60.png)

2023-02-20 09:57 UTC, mrCherry97 requested changes
typing `cmk +k` and `ns all` navigates all the time to namespace overview, when I am on for example Pods view and type in command pallet `ns all` I need to have two options: switch (redirect to pods view for all namespaces) and navigate (redirect to namespace overview)

2023-02-21 07:33 UTC, mrCherry97 approved these changes

2023-02-21 07:33 UTC, mrCherry97 approved these changes

2023-02-21 07:38 UTC, NHingerl commented on public/i18n/en.yaml
> +    all-namespaces: List resources from all namespaces
```suggestion
    all-namespaces: List resources from all Namespaces
```

Ignore this if we don't capitalize "Namespace" in Busola.

2023-02-21 07:40 UTC, mrCherry97 submitted a review, later dismissed

2023-02-21 07:43 UTC, NHingerl submitted a review, later dismissed

2023-02-21 07:58 UTC, mrCherry97 commented
/retest

2023-02-21 08:01 UTC, mrCherry97 commented
/retest

2023-02-21 08:38 UTC, mrCherry97 submitted a review, later dismissed

2023-02-21 08:53 UTC, mrCherry97 commented
/test pre-busola-integration-test-k3s-namespace

2023-02-21 08:56 UTC, NHingerl approved these changes

2023-02-21 09:15 UTC, NHingerl approved these changes

2023-02-21 09:57 UTC, mrCherry97 approved these changes

2023-02-21 10:25 UTC, merged