Widgets
kyma-project/busola pull request #2364
Opened 2023-02-23 07:20 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-02-27 07:21 UTC, qbalukom requested changes
This seems a bit PoC-ish for a merge to main... since it gets merged to main, should we provide slots for at least all the available resources?
Also, what about docs and schemas?

2023-02-27 07:21 UTC, qbalukom commented on src/components/Extensibility/components-widget/Widget.js
> +import React from 'react';
What's the reason for this file, when it's essentially identical to `components/Widget.js`?

2023-02-27 07:21 UTC, qbalukom commented on src/resources/Deployments/DeploymentDetails.js
> +);
(nitpick) some spacing around this might be nice, i guess?

2023-02-27 07:21 UTC, qbalukom commented on src/components/Extensibility/ExtensibilityWidgets.js
> +import { Widget } from './components-widget/Widget';
shouldn't we use `components/Widget` instead? to provide all the widgets, not just the table?

2023-02-27 07:21 UTC, qbalukom commented on src/state/types.ts
> +  destination: 'ClusterOverview' | 'Pods';
do we want to limit the choices in the type? especially when extensibility resources kick in?
i think both of these should simple be `string`

2023-02-27 07:21 UTC, qbalukom commented on src/components/Extensibility/ExtensibilityWidgets.js
> +export const ExtensibilityWidgetsCore = ({ resMetaData, root }) => {
Shouldn't this be called `ExtensibilityWidgetCore`, since it's the core of a single `ExtensibilityWidget`, not `ExtensibilityWidgets`?

2023-03-01 10:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/busola?pullRequest=2364) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/busola?pullRequest=2364) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/busola?pullRequest=2364) it.</sub>

2023-03-14 07:35 UTC, akucharska commented
/retest

2023-03-14 11:07 UTC, qbalukom requested changes

2023-03-15 07:47 UTC, qbalukom approved these changes

2023-03-15 08:41 UTC, akucharska commented
/retest

2023-03-15 11:01 UTC, akucharska commented
/retest

2023-03-15 11:45 UTC, IwonaLanger commented on docs/extensibility/display-section.md
> +  - [_injections_ Example](#injections-example)
```suggestion
  - [_injections_ example](#injections-example)
```

2023-03-15 11:45 UTC, IwonaLanger commented on docs/extensibility/display-section.md
> +To use widget injections with extension views use **general.resource.kind** as a **location**
```suggestion
Use **general.resource.kind** as a **location** for widget injections with extension views.
```

2023-03-17 07:04 UTC, qbalukom approved these changes

2023-03-17 07:05 UTC, merged