Create shortcut for Yaml Upload
kyma-project/busola pull request #2377
Opened 2023-03-08 07:56 UTC by chriskari

**Description**

Changes proposed in this pull request:

- Created a shortcut for Yaml Upload

**Related issue(s)**
#1713

2023-03-14 07:38 UTC, chriskari commented
/retest

2023-03-15 10:43 UTC, akucharska requested changes
When user types help, upload Yaml should be visible there. Please add it

2023-03-15 11:30 UTC, akucharska commented
/retest

2023-03-21 08:10 UTC, mrCherry97 commented
/retest

2023-03-21 08:13 UTC, akucharska approved these changes

2023-03-21 08:25 UTC, mrCherry97 commented
/retest

2023-03-21 09:53 UTC, mrCherry97 commented
/retest

2023-03-21 10:55 UTC, IwonaLanger approved these changes

2023-03-21 12:23 UTC, mrCherry97 commented
/retest

2023-03-21 12:36 UTC, merged