Get proper resource url based on permissions
kyma-project/busola pull request #2387
Opened 2023-03-15 07:00 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Get proper resource url based on permissions

**Related issue(s)**

2023-03-15 07:33 UTC, akucharska commented
/retest

2023-03-20 06:45 UTC, akucharska commented
/retest

2023-03-20 07:17 UTC, qbalukom requested changes

2023-03-20 07:17 UTC, qbalukom commented on src/components/Extensibility/helpers/jsonataWrapper.ts
> +  exp.registerFunction('canI', (resourceGroupAndVersion, resourceType) => {
shouldn't this function be documented?

2023-03-21 06:03 UTC, qbalukom submitted a review, later dismissed

2023-03-21 07:53 UTC, mrCherry97 commented
/retest

2023-03-21 08:14 UTC, akucharska commented
/retest

2023-03-21 10:06 UTC, akucharska commented
/test all

2023-03-21 10:32 UTC, akucharska commented
/retest

2023-03-21 10:42 UTC, IwonaLanger commented on docs/extensibility/jsonata.md
> +You can use this function to determine if user has access rights for listing specified resource.
```suggestion
You can use this function to determine if a user has access rights for listing a specified resource.
```

2023-03-21 10:42 UTC, IwonaLanger commented on docs/extensibility/jsonata.md
> +- **resourceGroupAndVersion** - first part of a resource url following the pattern: `${resource group}/${resource version}`.
```suggestion
- **resourceGroupAndVersion** - the first part of a resource URL following the pattern: `${resource group}/${resource version}`.
```

2023-03-21 10:42 UTC, IwonaLanger commented on docs/extensibility/jsonata.md
> +Example from the [ResourceList widget](display-section.md#resourcelist).
```suggestion
Here is an example from the [ResourceList widget](display-section.md#resourcelist):
```

2023-03-21 12:48 UTC, IwonaLanger approved these changes

2023-03-21 13:44 UTC, mrCherry97 commented
/retest

2023-03-21 13:55 UTC, mrCherry97 commented
/retest

2023-03-21 14:17 UTC, mrCherry97 commented
/retest

2023-03-21 14:40 UTC, merged