Widget for Kyma modules
kyma-project/busola pull request #2413
Opened 2023-03-27 07:35 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-03-28 06:48 UTC, akucharska commented
/retest

2023-03-28 09:15 UTC, akucharska commented
/retest

2023-03-29 09:53 UTC, mrCherry97 requested changes

2023-03-29 09:53 UTC, mrCherry97 commented on public/extensions/extensions.yaml
> +dataSources:
remove this, the rest looks fine

2023-03-29 12:56 UTC, mrCherry97 submitted a review, later dismissed

2023-03-29 13:07 UTC, IwonaLanger commented on docs/extensibility/display-section.md
> +- **resource** - To create a hyperlink, Busola needs the name and the kind of the target resource; they must be passed into the **resource** object as property paths in either **\$item** - value extr
```suggestion
- **resource** - To create a hyperlink, Busola needs the name and the kind of the target resource; they must be passed into the **resource** object as property paths in either **\$item** - value extracted using **source**, or **\$root** - the original resource. If the target resource is in a `namespace`, provide **Namespace**, **name**, and **kind** properties.
```

2023-03-29 13:22 UTC, IwonaLanger approved these changes

2023-03-29 13:43 UTC, mrCherry97 commented
/retest

2023-03-29 13:56 UTC, merged