Cleanup Dockerfiles, Makefiles etc of microfrontends
kyma-project/busola pull request #242
Opened 2021-06-23 13:55 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-06-25 13:05 UTC, valentinvieriu requested changes

2021-06-25 13:05 UTC, valentinvieriu commented on resources/kustomization.yaml
>    - kubernetes-dashboard-admin.yaml
Do we need this kubernetes-dashboar?

2021-06-25 13:06 UTC, valentinvieriu requested changes

2021-06-25 13:06 UTC, valentinvieriu commented on resources/kustomization.yaml
>  resources:
This file can be removed also

2021-06-25 13:06 UTC, Wawrzyn321 commented on Dockerfile-all
> +# this is a Dockerfile for single deployment app - both backend and frontends
Oh, I've renamed it on my previous PR. On it.

2021-06-25 13:06 UTC, Wawrzyn321 commented on resources/kustomization.yaml
>    - kubernetes-dashboard-admin.yaml
:pick:

2021-06-25 13:22 UTC, valentinvieriu approved these changes

2021-06-25 13:51 UTC, Wawrzyn321 commented
/retest

2021-06-25 13:54 UTC, valentinvieriu commented
/retest all

2021-06-25 14:18 UTC, Wawrzyn321 commented
/retest

2021-06-25 14:24 UTC, Wawrzyn321 commented
/test pre-busola-core

2021-06-25 15:04 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2021-06-26 04:49 UTC, Sawthis commented
/retest

2021-06-26 07:38 UTC, valentinvieriu commented
/retest

2021-06-26 07:56 UTC, valentinvieriu commented
/test pre-busola-integration-test-k3s

2021-06-27 04:56 UTC, valentinvieriu commented
/test pre-busola-integration-test-k3s

2021-06-28 05:11 UTC, valentinvieriu commented
/test pre-busola-integration-test-k3s

2021-06-28 05:34 UTC, merged