Static extensions
kyma-project/busola pull request #2443
Opened 2023-04-20 06:43 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-04-20 09:12 UTC, akucharska commented
/retest

2023-04-24 07:11 UTC, mrCherry97 requested changes

2023-04-24 07:11 UTC, mrCherry97 commented on public/extensions/statics.yaml
> +injections:
Move this to examples

2023-04-24 07:11 UTC, mrCherry97 commented on resources/web/configmap.yaml
> +          "EXTENSIBILITY_INJECTIONS": {
Revert this removed code

2023-04-24 11:44 UTC, mmitoraj reviewed
Please see my comments below :)

2023-04-24 11:44 UTC, mmitoraj commented on docs/extensibility/statics.md
> +This document describes the required ConfigMap setup that you need to configure in order to handle a static extension.
```suggestion
This document describes the required ConfigMap setup that you need to configure to handle a static extension.
```

2023-04-24 11:44 UTC, mmitoraj commented on docs/extensibility/statics.md
> +To define static extension add label `busola.io/extension:statics` to ConfigMap.
```suggestion
To define a static extension, add the `busola.io/extension:statics` label to the ConfigMap.
```

2023-04-24 11:44 UTC, mmitoraj commented on docs/extensibility/statics.md
> +> **NOTE:**: Busola supports only the two latest versions of the configuration. Whenever a new version of the configuration is proposed, go to your Extension and migrate your configuration to the lat
```suggestion
> **NOTE:** Busola supports only the two latest versions of the configuration. Whenever a new version of the configuration is proposed, go to your Extension and migrate your configuration to the latest version.
```

2023-04-24 11:44 UTC, mmitoraj commented on docs/extensibility/statics.md
> +The **general** section is not required as static extensions present data that are not conected to any resource. Instead they may use information from page they are displayed on via variable `$embedR
```suggestion
The **general** section is not required as static extensions present data that are not connected to any resource. Instead, they may use information from the page they are displayed on via variable `$embedResource`.
```

2023-04-24 11:44 UTC, mmitoraj commented on docs/extensibility/statics.md
> +For more information read [widget _injections_ overview](display-section.md#widget-injections-overview).
```suggestion
For more information read the [widget injections overview](display-section.md#widget-injections-overview).
```

2023-04-24 11:44 UTC, mmitoraj commented on examples/statics/kibana-links.yaml
> +    - name: "Logs for namespace"
```suggestion
    - name: "Logs for Namespace"
```
should we capitalize it here as in our docs?

2023-04-24 11:44 UTC, mmitoraj commented on examples/statics/kibana-links.yaml
> +    - name: "Logs for pod"
```suggestion
    - name: "Logs for Pod"
```
should we capitalize it here as in our docs?

2023-04-24 13:09 UTC, mrCherry97 approved these changes

2023-04-25 07:17 UTC, akucharska commented
/test all

2023-04-25 07:29 UTC, mmitoraj submitted a review, later dismissed

2023-04-25 07:48 UTC, mrCherry97 commented
/retest

2023-04-25 08:02 UTC, akucharska commented
/retest

2023-04-25 08:13 UTC, akucharska commented
/retest

2023-04-25 11:36 UTC, akucharska commented
/retest

2023-04-25 21:02 UTC, mrCherry97 commented
/retest

2023-04-26 08:47 UTC, halamix2 commented
/retest

2023-04-26 11:57 UTC, akucharska commented
/retest

2023-04-26 13:04 UTC, mrCherry97 commented
/retest

2023-04-26 13:19 UTC, mrCherry97 commented
/test pull-busola-backend-build

2023-04-26 13:25 UTC, mrCherry97 commented
/retest

2023-04-26 20:25 UTC, akucharska commented
/test all

2023-04-27 06:25 UTC, mrCherry97 commented
/retest

2023-04-27 06:45 UTC, mrCherry97 commented
/retest

2023-04-27 07:52 UTC, closed without merging