Use webcomponents in side navigation
kyma-project/busola pull request #2498
Opened 2023-06-14 07:21 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-08-08 10:47 UTC, akucharska commented
/retest

2023-08-09 07:06 UTC, akucharska commented
/retest

2023-08-09 07:50 UTC, mrCherry97 commented
/retest

2023-08-09 10:14 UTC, mrCherry97 requested changes
when I go to for example cluster role binding item in sidenav is marked
![image](https://github.com/kyma-project/busola/assets/46759954/88e58e31-d869-4c6a-8940-10bde475a04d)

but when I click for example on storage to close this category, crb should be still marked, but it's not
![image](https://github.com/kyma-project/busola/assets/46759954/d3c64fbd-5ca3-424e-918d-082b827b7ed2)

2023-08-09 10:14 UTC, mrCherry97 commented on tests/integration/support/generateRandomString.js
> +}
this function is not used anywhere, we need that?

2023-08-09 10:18 UTC, mrCherry97 requested changes
navigation for small device is not working, when I click for example on extensions then I'm not redirected anywhere
![image](https://github.com/kyma-project/busola/assets/46759954/b3890925-ece1-47f3-afad-ffb970313631)


Sidenav for small device is too small or there is unnecessary margin somewhere
![image](https://github.com/kyma-project/busola/assets/46759954/0bc817fe-4c6d-4727-a5e4-b55d354c1f2f)
old view, how it should look:
![image](https://github.com/kyma-project/busola/assets/46759954/0c8e8c1a-712d-4d96-bbf9-b9e44671c3a3)

2023-08-09 10:18 UTC, mrCherry97 commented on src/sidebar/CategoryItem.tsx
> +    );
Unnecesary console.log

2023-08-10 08:15 UTC, Akatuoro commented
> when I go to for example cluster role binding item in sidenav is marked
> but when I click for example on storage to close this category, crb should be still marked, but it's not

This is happening because of the default behaviour in the `SideNavigation` component.
On click (‘selection’), it sets every element’s `selected` property to false except the newly selected one:

https://github.com/SAP/ui5-webcomponents/blob/main/packages/fiori/src/SideNavigation.ts#L216C3-L216C3

When clicking on a category item, this gets overridden afterwards by `selected={false}`:

https://github.com/kyma-project/busola/pull/2498/files#diff-84924c1d7c5cbabdf412d1a40eebc3dfb1e736aaefb122a1a264d167e61e65c8R48

The solution is to register an event handler and prevent the default:
`<SideNavigation collapsed={isSidebarCondensed} onSelectionChange={(e) => e.preventDefault()}>`

2023-08-10 09:30 UTC, akucharska commented
/retest

2023-08-10 11:58 UTC, mrCherry97 approved these changes

2023-08-10 12:00 UTC, merged