Cluster validation
kyma-project/busola pull request #2531
Opened 2023-07-21 13:41 UTC by Akatuoro

**Description**

Changes proposed in this pull request:

- Add a cluster validation section in the cluster overview page
  - It is hidden behind a `CLUSTER_VALIDATION` feature flag
- The section enables a scan of the cluster
  - The scan validates the cluster resources against the rules of #2435
  - The user can configure which namespaces to scan and which policies to check
    - System namespaces like kube-system and kyma-system are excluded by default.
    - By default, the policies chosen by the user and cluster for resource validation are used
  - The user can configure the number of parallel requests to the api, 5 by default
- The scan result is shown as a tree where the user can drill down to the specific warnings
- This feature uses ui5 react webcomponents, so it includes the ui5 react webcomponent libraries and sets the necessary ThemeProvider
- The pqueue library is included for queuing requests and work for the worker thread

**Related issue(s)**

Resolves #2376

2023-07-27 11:00 UTC, mrCherry97 requested changes
Scan Progress shouldn't be displayed if a user is not scanning cluster.

When I provide `Parallel Requests` <= 0 then UI breaks.

We have a talk to add button for choose all namespaces and uncheck all.

It will be nice to have some margin/padding here:
![image](https://github.com/kyma-project/busola/assets/46759954/15bcc32d-f4f3-4ef7-9e5b-e03f55f293bf)

Info about feature flag should be added in docs and you can add it to defaultConfig with enabled false for now.

Why you are implementing TypeScript and JavaScript mixed? `ClusterValidation.js` rest of new files are `ts`.

2023-07-27 17:33 UTC, Akatuoro commented
> * [x]  Scan Progress shouldn't be displayed if a user is not scanning cluster.

Adjusted so that both Scan Progress and Scan Result is not shown if not available.

> * [x]  When I provide `Parallel Requests` <= 0 then UI breaks.

Fixed

> * [ ]  We have a talk to add button for choose all namespaces and uncheck all.

will work on that tomorrow

> * [x]  It will be nice to have some margin/padding here:
>   ![image](https://user-images.githubusercontent.com/46759954/256514988-15bcc32d-f4f3-4ef7-9e5b-e03f55f293bf.png)

done

> * [x]  Info about feature flag should be added in docs and you can add it to defaultConfig with enabled false for now.

done

> * [x]  Why you are implementing TypeScript and JavaScript mixed? `ClusterValidation.js` rest of new files are `ts`.

Good point, I've changed `ClusterValidation.js` to `tsx` and `ResourceValidation.worker.js` to `ts`.
I had it in `js` for faster iteration with components that are not well typed. Also needed to update the fundamental-react types, but now it's working well.

There is still 1 file in `js`:
`ClusterValidationConfiguration.js` - this is explicitly in `js` because the `ResourceForm` does not have proper types. So it is very verbose to assign all `ResourceForm` properties in `ts`.

2023-07-28 10:58 UTC, mrCherry97 requested changes
When I am a user with reduced permissions only for one namespace I can't list namespaces, but ClusterValidation feature is displaying all of them.
![image](https://github.com/kyma-project/busola/assets/46759954/0c7e802d-ebd4-448d-9596-6dad192b0f39)

![image](https://github.com/kyma-project/busola/assets/46759954/7501db2a-d629-4b3b-9a2f-2166f9ad19ec)

User should be able to see only this namespace where he has access.

2023-07-28 10:59 UTC, mrCherry97 commented
And also parallel <0 has no sense

2023-07-28 12:45 UTC, Akatuoro commented
> When I am a user with reduced permissions only for one namespace I can't list namespaces, but ClusterValidation feature is displaying all of them. ![image](https://user-images.githubusercontent.com/46759954/256803096-0c7e802d-ebd4-448d-9596-6dad192b0f39.png)
> 
> User should be able to see only this namespace where he has access.

Explanation: The restricted user has no access to /api/v1/namespaces , so the response status code is 403. This is counted as an error, so it goes into [processError](https://github.com/kyma-project/busola/blob/main/src/shared/hooks/BackendAPI/useGet.js#L77-L82) instead of [processDataFn](https://github.com/kyma-project/busola/blob/main/src/shared/hooks/BackendAPI/useGet.js#L74-L76)

I've included a fix for `useAvailableNamespaces`.

2023-07-28 13:54 UTC, Akatuoro commented
> And also parallel <0 has no sense

I've added a resource form validation for this. It is still possible to submit with <= 0, in which case the scan uses 1 connection.
![Screenshot 2023-07-28 at 15 53 55](https://github.com/kyma-project/busola/assets/4891926/cb2eabab-2f13-491f-8ef7-162bec1806f4)

2023-08-02 10:16 UTC, mrCherry97 requested changes
We need to have some tests for that functionality.

2023-08-03 17:49 UTC, Akatuoro commented
> We need to have some tests for that functionality.

I've added tests for the scan

2023-08-04 07:09 UTC, mrCherry97 commented
/test all

2023-08-04 08:15 UTC, Akatuoro commented
/retest

2023-08-04 08:17 UTC, mrCherry97 commented
/ok-to-test

2023-08-04 08:17 UTC, mrCherry97 commented
/test all

2023-08-04 11:35 UTC, mrCherry97 commented
/retest

2023-08-04 12:54 UTC, mrCherry97 commented
/test all

2023-08-04 13:18 UTC, mrCherry97 commented
/retest

2023-08-04 13:40 UTC, mrCherry97 commented
/retest

2023-08-04 15:23 UTC, Akatuoro commented
/retest

2023-08-08 11:24 UTC, akucharska reviewed
It looks really good.
My only suggestion is adding some additional styling for better looks

2023-08-08 11:24 UTC, akucharska commented on src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidation.tsx
> +          <FlexBox>
Consider adding padding to the flexbox
```suggestion
                    <FlexBox className="fd-has-padding-small">
```

2023-08-10 06:50 UTC, mrCherry97 commented
/test all

2023-08-10 07:37 UTC, mrCherry97 commented
/test pull-busola-integration-namespace-k3d

2023-08-10 10:38 UTC, mrCherry97 approved these changes

2023-08-10 11:06 UTC, mrCherry97 commented
/retest

2023-08-10 11:16 UTC, IwonaLanger commented on docs/resource-validation/README.md
> +With the `CLUSTER_VALIDATION` [feature flag](../features.md) enabled, you can use these rules to scan existing resources in your cluster.
I'd use the same formatting for CLUSTER_VALIDATION as in `features.md`, that is, bold font. It's not a flag, right?

2023-08-10 12:09 UTC, IwonaLanger approved these changes

2023-08-10 12:32 UTC, mrCherry97 commented
/retest

2023-08-10 13:20 UTC, merged