Migrate messageBox to webcomponents
kyma-project/busola pull request #2544
Opened 2023-08-11 07:22 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-08-14 05:39 UTC, akucharska commented
/retest

2023-08-16 10:43 UTC, akucharska commented
/retest

2023-08-17 07:09 UTC, akucharska commented
/retest

2023-08-17 07:16 UTC, mrCherry97 requested changes

2023-08-17 07:16 UTC, mrCherry97 commented on tests/integration/tests/namespace/test-namespace-overview.spec.js
> +      // cy.contains('b', QUOTA_NAME).should('not.exist');
why it's commented?

2023-08-17 07:17 UTC, akucharska commented on src/components/App/IncorrectPath.js
> +      onClose={() => {}}
yes, onClose is required

2023-08-17 07:46 UTC, akucharska commented
/retest

2023-08-17 08:58 UTC, mrCherry97 approved these changes

2023-08-17 09:00 UTC, merged