Remove "Open in Grafana" button in logs view
kyma-project/busola pull request #2596
Opened 2023-09-27 13:45 UTC by a-thaler

**Description**

Changes proposed in this pull request:

The logging feature via Grafana was removed recently, see https://github.com/kyma-project/kyma/issues/15827
It was missed to remove the deep-link button in the container log view

- Remove the button from the container logs view
- ...
- ...

**Related issue(s)**

2023-09-27 14:14 UTC, NHingerl approved these changes

2023-09-28 07:23 UTC, mrCherry97 requested changes

2023-09-28 07:23 UTC, mrCherry97 commented on resources/backend/deployment.yaml
> +          image: europe-docker.pkg.dev/kyma-project/dev/busola-backend:PR-2596
you don't need to bump the backend (your changes are only related to frontend), please revert that

2023-09-28 07:35 UTC, mrCherry97 approved these changes

2023-09-28 08:00 UTC, mrCherry97 commented
/retest

2023-09-28 08:01 UTC, NHingerl approved these changes

2023-09-28 08:56 UTC, merged