fix extensibility badges
kyma-project/busola pull request #2694
Opened 2023-12-14 13:46 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- fix displaying badges, bring back old naming convention.

**Related issue(s)**

2023-12-15 10:55 UTC, grego952 submitted a review, later dismissed

2023-12-15 11:16 UTC, chriskari commented on examples/injections/functions.yaml
> +          negative:
shouldn't this one be called "warning" for consistency with the documentation and the other files?

2023-12-15 11:16 UTC, chriskari commented on public/schemas/schema-details.yaml
> +            negative:
"warning" here as well?

2023-12-15 12:14 UTC, chriskari approved these changes

2023-12-15 12:34 UTC, akucharska requested changes
Change also in:

- examples/injections/apirules.yaml
- examples/services/configuration.yaml
- src/components/Extensibility/components/tests/Badge.test.js
- tests/integration/fixtures/examples/injections/apirules.yaml
- tests/integration/fixtures/examples/services/configuration.yaml

2023-12-15 12:34 UTC, akucharska commented on docs/extensibility/display-section.md
> +- rendered as critical: `error`, `failure`, `invalid`.
Change also in examples, line 233 and 837

2023-12-18 11:43 UTC, akucharska commented
/retest

2023-12-18 12:12 UTC, akucharska commented
/retest

2023-12-18 12:38 UTC, akucharska commented
/retest

2023-12-18 13:44 UTC, grego952 approved these changes

2023-12-18 13:46 UTC, merged