node view is similar to cluster view
kyma-project/busola pull request #2742
Opened 2024-01-23 15:22 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-01-24 07:38 UTC, dbadura commented
/retest

2024-01-24 18:13 UTC, mrCherry97 requested changes

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/MachineInfo/MachineInfo.js
> +      <div className="cluster-overview__graphs-wrapper">
this div with className is not necessary probably, after removing this nothing changed.

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/NodeDetails/NodeDetails.js
> +  console.log(data);
remove clg

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/NodeDetails/NodeDetails.js
> +import React from 'react';
this import is unused

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/NodeResources/NodeResources.js
> +      <div className="cluster-overview__graphs-wrapper">
everything is "packed" in `div` so `<>` this react fragment is unnecessary.
```suggestion
      <div className="cluster-overview__graphs-wrapper">
```

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/NodeResources/NodeResources.js
> +    </>
As the previous comment.
```suggestion
      </div>
```

2024-01-24 18:13 UTC, mrCherry97 commented on src/components/Nodes/NodeResources/NodeResources.js
> +                color="var(--sapIndicationColor_7)"
we need to talk about colors, idk if we want to have the same colors as on the cluster and namespace overview.

2024-01-25 13:12 UTC, dbadura commented
/retest

2024-01-25 14:18 UTC, dbadura commented
/retest

2024-01-25 14:57 UTC, dbadura commented
/retest

2024-01-25 15:27 UTC, dbadura commented
/retest

2024-01-26 08:22 UTC, dbadura commented
/retest

2024-01-26 09:31 UTC, mrCherry97 commented
/cla recheck

2024-01-26 10:04 UTC, halamix2 commented
/cla

2024-01-26 10:12 UTC, halamix2 commented
/cla

2024-01-26 12:26 UTC, akucharska commented on src/components/Clusters/views/ClusterOverview/ClusterNodes.js
> +import { ProgressIndicatorWithPercentage } from '../../../../shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage';
```suggestion
import { ProgressIndicatorWithPercentage } from 'shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage';
```

2024-01-26 13:56 UTC, nataliasitko approved these changes

2024-01-26 14:05 UTC, mrCherry97 approved these changes

2024-01-26 14:05 UTC, akucharska approved these changes

2024-01-26 17:40 UTC, mrCherry97 commented
/retest

2024-01-26 18:07 UTC, merged