Fix router link 3
kyma-project/busola pull request #2805
Opened 2024-03-01 15:07 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-03-04 10:38 UTC, OliwiaGowor requested changes
-  [ ] some links are not working for `All Namespaces` - the namespace in the url is being set to `-all-` (for example in `Replica Sets` and after clicking Controlled by)
<img width="1612" alt="Screenshot 2024-03-04 at 10 26 49" src="https://github.com/kyma-project/busola/assets/72342415/3db649fd-aa6b-4d8d-a622-a7fb6bb74a99">

2024-03-04 11:52 UTC, mrCherry97 commented
@OliwiaGowor `some links are not working for All Namespaces` it's another problem which needs to be resolved in separate task (we are using `useUrl` and `namespaceUrl`, we need to find out the solution how to take namespace from resource, not from the link.

The rest is adjusted, I forgot to bring back CSSes.

2024-03-05 07:24 UTC, akucharska approved these changes

2024-03-05 07:42 UTC, OliwiaGowor approved these changes

2024-03-05 07:44 UTC, merged