Replace 'a'  with 'ui5link'
kyma-project/busola pull request #2824
Opened 2024-03-13 12:15 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-03-13 13:16 UTC, dbadura commented
/test all

2024-03-13 15:43 UTC, dbadura commented on src/shared/components/DescriptionHint/DescriptionHint.js
> +          onAfterOpen={() => {
Suggestion to reviewer:
We can also use prop
```
          initialFocus={`descriptionOpener-${context}`}
```
instead of ref.

2024-03-13 15:53 UTC, dbadura commented
/retest

2024-03-13 16:01 UTC, dbadura commented
/retest

2024-03-18 14:40 UTC, dbadura commented on src/shared/components/ExternalLink/ExternalLink.tsx
> +  design = 'Emphasized',
Fixed

2024-03-18 14:42 UTC, dbadura commented on src/shared/components/ExternalLink/ExternalLink.tsx
> +  className = '',
It's used here: https://github.com/kyma-project/busola/blob/ce1983ab248165b67331515cf2e797fcc1434963/src/shared/components/EmptyListComponent/EmptyListComponent.tsx#L60-L64

2024-03-19 08:50 UTC, dbadura commented on src/shared/components/ExternalLink/ExternalLink.tsx
> +  className = '',
Fixed

2024-03-19 10:19 UTC, mrCherry97 requested changes

2024-03-19 10:19 UTC, mrCherry97 commented on src/shared/components/ExternalLink/ExternalLink.tsx
> +export type LinkProps = {
now types don't need to be exported.

2024-03-19 10:28 UTC, mrCherry97 requested changes
- [ ] Icon is never used in `Modules.js`
- [ ] style in TokenRequestModal is no longer valid
- [ ] disabled prop should be added to CopiableText

2024-03-19 13:04 UTC, mrCherry97 submitted a review, later dismissed

2024-03-19 13:04 UTC, dbadura commented
/retest

2024-03-19 15:50 UTC, merged