Edit variables
kyma-project/busola pull request #283
Opened 2021-07-13 13:04 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-07-15 12:35 UTC, akucharska commented
/retest

2021-07-16 07:30 UTC, valentinvieriu commented
Please check https://github.com/kyma-project/kyma/issues/10311
I've added some ui changes in there.

2021-07-23 11:55 UTC, parostatkiem requested changes

2021-07-23 11:55 UTC, parostatkiem commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/ResourceVariableInput.js
> +      return {
You can use a direct object return as above

2021-07-23 11:55 UTC, parostatkiem commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/validation.test.js
> +  test('should return true if currentVariable valueFrom.name or key are present', () => {
```suggestion
  test('should return true if currentVariable valueFrom.name and key are present', () => {
```

2021-07-23 11:55 UTC, parostatkiem commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/validation.js
> +        varValue: variable.value ? variable.value : variable.valueFrom,
```suggestion
        varValue: variable.value || variable.valueFrom,
```

2021-07-23 12:23 UTC, parostatkiem approved these changes

2021-07-23 12:34 UTC, merged