Adjust upload yaml
kyma-project/busola pull request #2883
Opened 2024-04-15 06:44 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-04-16 11:25 UTC, dbadura reviewed
In other PR I will adjust Monaco scroll, scroll of the right side and upload finished view when I get the desings.

2024-04-18 13:49 UTC, dbadura commented
/retest

2024-04-19 07:08 UTC, dbadura commented
/retest

2024-04-19 08:11 UTC, dbadura commented
/retest

2024-04-22 06:42 UTC, dbadura commented
/retest

2024-04-23 06:44 UTC, akucharska requested changes
1. Is the font right size? 
![Screenshot 2024-04-23 at 08 38 13](https://github.com/kyma-project/busola/assets/20790348/424f1e84-e87f-48f0-bd0d-80ae7c9fa80d)
2. Is there a way to fix separator lines
3. The warning icon is not centered to the arrow of collapsible row
![Screenshot 2024-04-23 at 08 40 35](https://github.com/kyma-project/busola/assets/20790348/73362a97-cc8d-48b0-8966-d9134b81d71d)
4. There should be bigger space between title and text above it 
![Screenshot 2024-04-23 at 08 40 41](https://github.com/kyma-project/busola/assets/20790348/42fa395b-bbe4-41cd-af4d-7a43e28b91d3)

2024-04-23 06:44 UTC, akucharska commented on public/defaultConfig.yaml
> +      isEnabled: true
Should we set it to true?

2024-04-23 13:59 UTC, dbadura commented on public/defaultConfig.yaml
> +      isEnabled: true
Reverted

2024-04-25 06:25 UTC, dbadura commented on src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
> +                marginLeft: '-0.3125rem', //set icon in one line with expand arrow. The value from class `--_ui5-v1-20-0_panel_content_padding1` is divided by 2
Unfortunately I couldn't make it to work.

2024-04-25 10:01 UTC, merged