feat: AI-banner & banner-carousel
kyma-project/busola pull request #2888
Opened 2024-04-19 11:54 UTC by chriskari

**Description**

Changes proposed in this pull request:

- adjusted FeatureCard to be able to have different illustrations & background-styles
- adjusted Injections to display multiple FeatureCards in a Carousel-component
- adjusted documentation
- code clean-up for isSystemThemeDark function

**Related issue(s)**

2024-04-23 06:15 UTC, mrCherry97 reviewed
LGTM

2024-04-23 06:24 UTC, mrCherry97 requested changes

2024-04-23 06:24 UTC, mrCherry97 commented on src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
> +      const decoded = jwtDecode(token);
when I'm not an SAP user, the AI banner is shown.

2024-04-23 06:41 UTC, mrCherry97 requested changes

2024-04-23 06:41 UTC, mrCherry97 commented on src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
> +  const isSAPuser = token => {
This function should be registered as jsonata function, same like we have the rest of the functions in `jsonataWrapper`

2024-04-24 08:05 UTC, akucharska approved these changes

2024-04-25 07:53 UTC, merged