feat: adjust Cron Jobs
kyma-project/busola pull request #2969
Opened 2024-06-13 09:05 UTC by OliwiaGowor

**Description**

Changes proposed in this pull request:

- adjusted data displayed on the Cron Jobs details:
   - moved Last Schedule Time and Last Job execution to status
   - added active, lastScheduleTime, lastSuccessfulTime to status card
   - moved Events to be right above the graphs

**Related issue(s)**

2024-06-13 11:36 UTC, mrCherry97 requested changes
- [ ] Create for Jobs should be removed, we need to remove create button from all the places in details:
![image](https://github.com/kyma-project/busola/assets/46759954/4eb05a45-290b-464b-b8c2-3cb0b93d5a52)
- [x] I have provided more data to spec, and it's not displayed anywhere, consider adding `spec` panel with all of the information from `spec` and move information from metadata card there (remember about default values if value if not provided)
```
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 1
  suspend: false
```
- [x] add information how often cronJob is scheduled like we have it in form
suggestion: 
![image](https://github.com/kyma-project/busola/assets/46759954/0d13869f-1fba-4101-bc9b-78f109193cf5)

In my namespace this CronJob is created, but edited to be triggered yearly, to not kill the cluster.
YAML example:
```
kind: CronJob
apiVersion: batch/v1
metadata:
  name: hello
  namespace: mw
  labels:
    app.kubernetes.io/name: hello
spec:
  schedule: * * * * *
  startingDeadlineSeconds: 1
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: hello
              image: busybox
              command:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
status:
  lastScheduleTime: '2024-06-13T11:30:00Z'
  lastSuccessfulTime: '2024-06-13T11:30:03Z'
```

2024-06-13 11:57 UTC, mrCherry97 commented
changes with spec data will be made as follow up in next tasks.

2024-06-14 08:35 UTC, mrCherry97 approved these changes

2024-06-14 08:38 UTC, nataliasitko approved these changes

2024-06-14 08:40 UTC, merged