fix: Fix tests after changing gardener flow
kyma-project/busola pull request #3058
Opened 2024-07-12 06:42 UTC by OliwiaGowor

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2024-07-15 10:23 UTC, mrCherry97 requested changes

2024-07-15 10:23 UTC, mrCherry97 commented on tests/integration/tests/cluster/test-cluster-configuration.spec.js
> +    // Uncomment after bringing back overriting storage
overriting storage is working

2024-07-15 14:24 UTC, dbadura submitted a review, later dismissed

2024-07-16 12:11 UTC, mrCherry97 approved these changes

2024-07-16 12:28 UTC, merged