feat: External navigation nodes as part of extensibility
kyma-project/busola pull request #3075
Opened 2024-07-18 06:18 UTC by OliwiaGowor

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

**Definition of done**

- [ ] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [ ] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [ ] Explain clearly why you created the PR and what changes it introduces
- [ ] All necessary steps are delivered, for example, tests, documentation, merging

2024-07-24 08:04 UTC, mrCherry97 requested changes
```
  externalNodes:
    - category: TEST123
      children:
        - label: TEST_LABEL
          link: 'http://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/kyma-cr.md'
```
NavItem:73
![image](https://github.com/user-attachments/assets/c311c401-0c98-48cd-b603-03519eac226d)

2024-07-24 08:46 UTC, mrCherry97 requested changes

2024-07-24 08:46 UTC, mrCherry97 commented on docs/extensibility/resources.md
> +  - **icon** - an optional icon
We need to provide an information where user can find a list of the available icons

2024-07-24 08:48 UTC, mrCherry97 requested changes
Icons are not working 
```
  externalNodes:
    - category: TEST123
      scope: namespace
      children:
        - label: TEST_LABEL_KYMA1
          link: '$string(($apiRules().items.spec.host)[0])'
          icon: accidental-leave
        - icon: competitor
          label: TEST_LABEL_KYMA2
          link: 'www.google.com'
```
![image](https://github.com/user-attachments/assets/6eeae104-d1d1-4435-9da6-210c560c2a5e)

2024-07-24 09:00 UTC, mrCherry97 requested changes

2024-07-24 09:00 UTC, mrCherry97 commented on src/sidebar/NavItem.tsx
> +  }, [jsonata, node.externalUrl]);
Infinite loop, remove useEffect

2024-07-24 09:11 UTC, mrCherry97 requested changes

2024-07-24 09:11 UTC, mrCherry97 commented on src/components/Extensibility/contexts/DataSources.tsx
>        namespace = resource.metadata.namespace;
```suggestion
    if (typeof namespace === 'undefined') {
      namespace = resource?.metadata?.namespace;
```

2024-07-24 09:11 UTC, mrCherry97 commented on src/sidebar/NavItem.tsx
> +        link = link.startsWith('http') ? link : `https://${link}`;
it's not working

2024-07-24 09:58 UTC, mrCherry97 approved these changes

2024-07-24 10:00 UTC, mrCherry97 requested changes

2024-07-24 10:00 UTC, mrCherry97 commented on docs/extensibility/resources.md
> +        link: 'https://github.com/kyma-project/busola' & $string($exampleResource().link)
```suggestion
externalNodes:
  - category: My Category
    icon: course-book
    children:
      - label: Example Node Label
        link: 'https://github.com/kyma-project/busola'
  - category: My Second Category
    icon: bar-chart
    scope: namespace
    children:
      - label: Example Node Label
        link: '$string($exampleResource().link)'
```

2024-07-24 11:51 UTC, grego952 commented on docs/extensibility/resources.md
> +- **externalNodes** - a optional list of links to external websites.
```suggestion
- **externalNodes** - an optional list of links to external websites.
```

2024-07-24 11:51 UTC, grego952 commented on docs/extensibility/resources.md
> +    - **link** - a link to external website. A [JSONata](jsonata.md) function can be provided.
```suggestion
    - **link** - a link to an external website. You can provide a [JSONata](jsonata.md) function.
```

2024-07-24 11:51 UTC, grego952 commented on docs/extensibility/resources.md
> +  - **icon** - an optional icon. You can find the list of available icons [here](https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview)
```suggestion
  - **icon** - an optional icon. Go to [Icon Explorer](https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview) to find a list of the available icons.
```

2024-07-24 11:58 UTC, grego952 approved these changes

2024-07-26 06:56 UTC, mrCherry97 approved these changes

2024-07-26 07:06 UTC, merged