feat: Enhance Config Maps
kyma-project/busola pull request #3300
Opened 2024-08-26 10:34 UTC by OliwiaGowor

**Description**

Changes proposed in this pull request:

- feat: added binaryData to Config Map details
- feat: add encode/decode base64 to `ReadonlyEditorPanel`

**Related issue(s)**

**Definition of done**

- [x] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [x] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [x] Explain clearly why you created the PR and what changes it introduces
- [x] All necessary steps are delivered, for example, tests, documentation, merging

2024-08-27 09:27 UTC, akucharska approved these changes

2024-08-27 09:28 UTC, akucharska requested changes
I approved wrong PR

2024-08-27 09:36 UTC, mrCherry97 requested changes
resource graph is not working, it should display connected pod when user will provide ownerReference to metadata

2024-08-28 07:11 UTC, mrCherry97 approved these changes

2024-08-28 07:22 UTC, merged