enable luigi backdrop and add info
kyma-project/busola pull request #332
Opened 2021-08-11 08:15 UTC by qbalukom

**Description**
Changes proposed in this pull request:
- add luigi overlay when dialog is open
- add an information box when disabling confirmations

2021-08-11 09:15 UTC, Wawrzyn321 approved these changes

2021-08-11 10:05 UTC, Wawrzyn321 approved these changes

2021-08-12 06:06 UTC, Sawthis requested changes
Please add Polish translation as well.

2021-08-12 06:34 UTC, qbalukom commented
/test pre-busola-web

2021-08-12 06:53 UTC, NHingerl commented on core/src/i18n/en.yaml
> +    information: Delete confirmations will be disabled for all resources. It can be turned back on in Preferences.
```suggestion
    information: You've switched off delete confirmations for all resources. You can switch them back on in **Preferences**.
```
I suggest active voice and no future tense. Not sure whether we can/want to use bold type here, thus only a suggestion, not editing myself.

2021-08-12 07:50 UTC, Sawthis approved these changes

2021-08-12 09:48 UTC, NHingerl approved these changes

2021-08-12 09:53 UTC, merged