Move preferences view to modal
kyma-project/busola pull request #333
Opened 2021-08-11 08:26 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- Move Preferences to microfrontend-based modal.
- Allow to open Preferences without a cluster chosen.

**Related issue(s)**

2021-08-11 11:35 UTC, dariadomagala commented on core/src/luigi-config/navigation/navigation-data-init.js
> +        openNodeInModal: { title: 'Preferences', size: 'm' },
I believe we should start moving such texts into the i18n files

2021-08-11 13:26 UTC, dariadomagala commented on core/src/i18n/en.yaml
> +navigation:
maybe a `profile`/`profile-dropdown` instead of `navigation`? that's how the dropdown is called in the sap/luigi world :)

2021-08-11 13:45 UTC, Wawrzyn321 commented
/retest

2021-08-11 13:47 UTC, dariadomagala approved these changes

2021-08-11 13:48 UTC, dariadomagala requested changes
please add also polish translations

2021-08-11 13:58 UTC, dariadomagala submitted a review, later dismissed

2021-08-12 06:04 UTC, Sawthis approved these changes

2021-08-12 06:47 UTC, NHingerl approved these changes

2021-08-12 07:04 UTC, akucharska approved these changes

2021-08-12 07:05 UTC, merged