BTP ServiceBindings & ServiceInstances
kyma-project/busola pull request #348
Opened 2021-08-19 14:14 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBindingData.js
> +      value: status.bindingID || t('common.messages.not-set'),
maybe just `-` (EMPTY_TEXT_PLACEHOLDER) ?

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/components/Predefined/Details/ServiceInstance/ServiceInstance.details.js
> +        ServiceBindingList,
We don't need the `service instance name` column on a service instance details view here. The user will know what instance it refers to.

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/components/Predefined/Details/ServiceInstance/ServiceInstanceData.js
> +    <DefinitionList title="Instance Data" list={list} key="instance-data" />
The title should come from the i18n file. Also, imho it should be `Service Instance data`.

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBindingData.js
> +  const navigateToSecret = secretName =>
sometimes such secret doesn't exist, and it redirects the user to a non-existing page. Could we somehow distinguish if we should only show a name or a link?

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/components/Predefined/List/ServiceInstances.list.js
> +      header: 'Offering name',
Please use i18n translations here.

2021-08-23 11:45 UTC, dariadomagala commented on core-ui/src/shared/components/ServiceInstanceStatus.js
> +export function ServiceInstanceStatus({ serviceInstance }) {
cannot we join this file with Service Bindings statuses?

2021-08-24 05:49 UTC, dariadomagala requested changes

2021-08-24 05:49 UTC, dariadomagala commented on core/src/luigi-config/navigation/static-navigation-model.js
> +        requiredFeatures: [features.BTP_CATALOG],
something doesn't work here. those two entries are shown even on a cluster without BTP resources

2021-08-24 08:37 UTC, dariadomagala submitted a review, later dismissed

2021-08-24 08:57 UTC, NHingerl approved these changes

2021-08-24 08:58 UTC, dariadomagala approved these changes

2021-08-24 09:03 UTC, merged