Ui5 migrate v2
kyma-project/busola pull request #3542
Opened 2024-12-17 11:33 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

**Definition of done**

- [ ] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [ ] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [ ] Explain clearly why you created the PR and what changes it introduces
- [ ] All necessary steps are delivered, for example, tests, documentation, merging

2025-01-03 09:31 UTC, mrCherry97 reviewed
Part of the review (253/307 files checked). Please take a look: 

- [ ] `CommandPallete` shouldn't be able to navigate when Create/Edit modal is filled )please also open an issue to add this to test cases or add it)

https://github.com/user-attachments/assets/7fce6e56-5fb0-40d1-974d-48f9b5aa9c1d

- [ ] Something is wrong with Edit form (mostly on Modules view), when I make some changes, and wait for like 5-6 seconds, modal is refreshed to initial state, I can click `Add`, but there are no changes

https://github.com/user-attachments/assets/dba6520c-a14b-4080-9cc0-af9c096507fd

- [ ] Presets are not working, clicking arrow is marking `Name` label, and I can't write anything (we should have to choose some preset in the tests)

https://github.com/user-attachments/assets/10312eb4-9cce-42e4-9f61-f099ebd5e5f6

2025-01-03 09:41 UTC, OliwiaGowor commented on src/components/Clusters/views/ClusterOverview/ClusterOverview.js
> +              size="H3"
The `level` prop defines the header level, so it is mainly used for accessibility purposes

2025-01-03 11:18 UTC, mrCherry97 reviewed
Finish of my review.
- [ ] Something is wrong with dropdowns/options (Check APIRules service dropdown)
![image](https://github.com/user-attachments/assets/cde7a94d-f89e-4603-bd8a-b6499204eb3a)

Also after choosing some of the option, empty option is displayed 
![image](https://github.com/user-attachments/assets/8056168b-3750-4e9e-a7a2-be496fc259d5)

Last option is most of the time empty (API Rules -> Access Strategy):
![image](https://github.com/user-attachments/assets/e8c1ddf6-73d0-4653-bfcb-0776ab9c2bc7)

- [ ] Check styles of the header in Modules view
New:
![image](https://github.com/user-attachments/assets/9e484be7-b5e2-4a85-8b22-4bfa637d19e5)

Old:
![image](https://github.com/user-attachments/assets/85511166-db68-42b3-a807-fbe0b0a8bc5a)

2025-01-03 11:18 UTC, mrCherry97 commented on src/shared/components/GenericList/components.js
> +    <TableRow type="Active" selected={isSelected}>
Just question, `navigated` prop should be removed?

2025-01-03 11:18 UTC, mrCherry97 commented on src/shared/components/ResourceDetails/ResourceDetails.scss
> -@container (min-width: 650px) {
Search for the rest of `@container` and check if it's working, there is 16 results in 10 files

2025-01-09 12:27 UTC, akucharska requested changes

2025-01-13 06:12 UTC, KonradPietocha commented on src/components/KymaModules/KymaModulesAddModule.js
> +          design="Critical"
Maybe in the future it would be good if we had consts (enums or objects) for repeating values ​​and used them. Then when the value changes, we change it in one place and it works everywhere.

2025-01-13 06:21 UTC, KonradPietocha commented on src/state/useAfterInitHook.ts
> -    if (!cluster === undefined) {
I think it will be more readable: "cluster !== undefined" or "cluster != undefined" if we want to exclude null as well or just "if(cluster)" if an empty string is also not a desired value

2025-01-20 12:28 UTC, OliwiaGowor commented on src/shared/ResourceForm/components/ModeSelector.js
> +          const mode = event.detail.selectedItems[0].getAttribute('data-mode');
Yes, because in the case of the Mode Selector, we can't have multiple modes selected (both YAML and Form), so it will always be the first element

2025-01-20 13:08 UTC, OliwiaGowor commented on src/state/useAfterInitHook.ts
> -    if (!cluster === undefined) {
This comparison was confusing since it first checked if `cluster` is truthy and then compared it to `undefined`. Our goal here was to check if there was still no cluster. After the migration, this line started messing with the saving previous path functionality.

2025-01-21 13:43 UTC, mrCherry97 reviewed
- [x] Clicking APIGateway on the Cluster level is causing busola break
![image](https://github.com/user-attachments/assets/4d28cf42-a37f-44b5-8276-cc2e63d61dc3)

2025-01-21 13:43 UTC, mrCherry97 commented on src/components/KymaModules/KymaModulesList.js
> +            <Tag className="sap-margin-begin-tiny" hideStateIcon>
design should be added, Critical probably, but need to check

2025-01-21 13:43 UTC, mrCherry97 commented on src/components/KymaModules/KymaModulesList.js
> +            <Tag className="sap-margin-begin-tiny" hideStateIcon>
I found, colorScheme = 3, design = set2 probably

2025-01-21 13:43 UTC, mrCherry97 commented on src/shared/components/Labels/Labels.js
> +            hideStateIcon={hideIcon}
`design = set2` looks better, and more like previously

2025-01-23 07:35 UTC, akucharska submitted a review, later dismissed
lgtm

2025-01-23 12:43 UTC, grego952 commented on docs/contributor/testing-strategy.md
> +- `PR Unit and Component Tests / run-unit-and-component-test` - Performs unit tests and component tests of Busola.
```suggestion
- `PR Unit and Component Tests / run-unit-and-component-test` - Performs unit and component tests of Busola.
```

2025-01-24 08:02 UTC, mrCherry97 commented
/hold until https://github.com/kyma-project/busola/pull/3598

2025-01-27 08:23 UTC, mrCherry97 commented
/unhold

2025-01-27 08:50 UTC, grego952 approved these changes

2025-01-29 08:44 UTC, grego952 approved these changes

2025-01-29 09:01 UTC, akucharska approved these changes

2025-01-29 09:04 UTC, merged