feat: Add documentation about busola in k8s and adjust k8s configs
kyma-project/busola pull request #3547
Opened 2024-12-18 12:49 UTC by dbadura

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

**Definition of done**

- [ ] The PR's title starts with one of the following prefixes:
  - feat: A new feature
  - fix: A bug fix
  - docs: Documentation only changes
  - refactor: A code change that neither fixes a bug nor adds a feature
  - test: Adding tests
  - chore: Maintainance changes to the build process or auxiliary tools, libraries, workflows, etc.
- [ ] Related issues are linked. To link internal trackers, use the issue IDs like `backlog#4567`
- [ ] Explain clearly why you created the PR and what changes it introduces
- [ ] All necessary steps are delivered, for example, tests, documentation, merging

2025-01-03 13:10 UTC, akucharska reviewed
lgtm

2025-01-07 09:03 UTC, pbochynski requested changes
I followed the instruction to deploy busola to local k3d cluster, but I failed to access this cluster from busola. Probably the latest image does not include all the changes required to work properly. I've seen also some errors to fetch localhost:3001/backend, even though my busola is hosted on port 80.

2025-01-07 09:04 UTC, grego952 commented on README.md
> +To install Busola on Kubernetes cluster run:
```suggestion
To install Busola on the Kubernetes cluster, run:
```

2025-01-07 09:05 UTC, grego952 commented on README.md
> +## Deploy Busola in Kubernetes Cluster
```suggestion
## Deploy Busola on the Kubernetes Cluster
```

2025-01-07 09:07 UTC, grego952 commented on README.md
> +To install Busola using specific environment configuration, set `ENVIRONMENT` shell environment variable and run:
```suggestion
To install Busola using a specific environment configuration, set the `ENVIRONMENT` shell environment variable and run:
```

2025-01-07 09:07 UTC, grego952 commented on README.md
> +## Access Busola installed on Kubernetes
```suggestion
## Access Busola Installed on Kubernetes
```

2025-01-07 09:07 UTC, grego952 commented on README.md
> +### Kubectl
```suggestion
### kubectl
```

2025-01-07 09:08 UTC, grego952 commented on README.md
> +The simplest method which always works is to use capabilities of `kubectl`.
```suggestion
The simplest method that always works is to use the capabilities of kubectl.
```

2025-01-07 09:08 UTC, grego952 commented on README.md
> +### Busola installed on K3d
```suggestion
### k3d
```

2025-01-07 09:17 UTC, grego952 commented on README.md
> +- K3d with installed Traefik, by default it's installed.
```suggestion
- k3d with [Traefik](https://k3d.io/v5.6.0/usage/k3s/#traefik) (installed by default).
```

2025-01-07 09:19 UTC, grego952 commented on README.md
> +Install ingress resources by running:
```suggestion
1. Install Ingress resources:
```

2025-01-07 09:19 UTC, grego952 commented on README.md
> +Go to `localhost`
```suggestion
2. Go to `localhost`
```

2025-01-07 09:19 UTC, grego952 commented on README.md
> +### Kubernetes cluster with Istio installed
```suggestion
### Kubernetes Cluster with Istio Installed
```

2025-01-07 09:22 UTC, grego952 commented on README.md
> +- Sidecar Proxy injection enabled, see [Kyma docs](https://kyma-project.io/#/istio/user/tutorials/01-40-enable-sidecar-injection?id=enable-istio-sidecar-proxy-injection), how to enable it.
```suggestion
- Sidecar Proxy injection enabled, see [Enable Istio Sidecar Proxy Injection](https://kyma-project.io/#/istio/user/tutorials/01-40-enable-sidecar-injection?id=enable-istio-sidecar-proxy-injection).
```

2025-01-07 09:23 UTC, grego952 commented on README.md
> +- Api gateway module installed, see [install docs](https://kyma-project.io/#/02-get-started/01-quick-install)
```suggestion
- The API Gateway module installed, see [Quick Install](https://kyma-project.io/#/02-get-started/01-quick-install)
```

2025-01-07 09:24 UTC, grego952 commented on README.md
> +Install Istio needed resources by running:
```suggestion
1. Install the Istio required resources:
```

2025-01-07 09:24 UTC, grego952 commented on README.md
> +To get Busola address run:
```suggestion
2. To get the Busola address, run:
```

2025-01-07 09:25 UTC, grego952 commented on README.md
> +and find `busola-***` virtual service. Under `HOSTS` there is address to access Busola page.
```suggestion
and find the `busola-***` virtual service. Under `HOSTS,` there is an address where you can access the Busola page.
```

2025-01-07 10:57 UTC, pbochynski commented on resources/base/busola/hpa.yaml
>  spec:
The target for HPA does not exist:
```
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
```

2025-01-08 08:05 UTC, pbochynski approved these changes

2025-01-08 09:52 UTC, grego952 commented on README.md
> +  > More details available in k3d docs [exposing services](https://k3d.io/v5.6.3/usage/exposing_services/).
```suggestion
  > See [Exposing Services](https://k3d.io/v5.6.3/usage/exposing_services/) for more details.
```

2025-01-08 09:52 UTC, grego952 commented on README.md
> +2. Go to `localhost`
Now that I think of it. What does it mean?
Go to the localhost folder? Something else?

2025-01-08 09:52 UTC, grego952 commented on README.md
> +#### Connect to the k3d cluster where Busola is installed.
```suggestion
#### Connect to the k3d Cluster With Busola Installed.
```

2025-01-08 09:52 UTC, grego952 commented on README.md
> +To be able to connect to the same K3d cluster where Busola is installed.
```suggestion
To connect to the same k3d cluster with Busola installed, download kubeconfig and change the cluster server address to `https://kubernetes.default.svc:443`.
```

2025-01-08 09:52 UTC, grego952 commented on README.md
> +Using shell.
To do what? Maybe we don't need this sentence.

2025-01-08 09:52 UTC, grego952 commented on README.md
> +Download kubeconfig and change cluster server address to `https://kubernetes.default.svc:443`.
```suggestion
```

2025-01-08 09:52 UTC, grego952 commented on README.md
> +Set `K3D_CLUSTER_NAME` shell environment variable to name of your cluster and run:
```suggestion
Set the `K3D_CLUSTER_NAME` shell environment variable to the name of your cluster and run:
```

2025-01-08 10:46 UTC, grego952 commented on README.md
> +## Deploy Busola on the Kubernetes Cluster
```suggestion
## Deploy Busola in the Kubernetes Cluster
```

2025-01-08 10:46 UTC, grego952 commented on README.md
> +To install Busola on the Kubernetes cluster, run:
```suggestion
To install Busola in the Kubernetes cluster, run:
```

2025-01-08 11:29 UTC, pbochynski approved these changes

2025-01-08 13:46 UTC, grego952 submitted a review, later dismissed

2025-01-08 13:49 UTC, pbochynski approved these changes

2025-01-14 07:57 UTC, grego952 approved these changes

2025-01-14 08:13 UTC, mrCherry97 approved these changes

2025-01-14 10:17 UTC, mrCherry97 commented
/override tide

2025-01-14 10:17 UTC, merged