Certificates and issuers
kyma-project/busola pull request #387
Opened 2021-09-06 06:22 UTC by qbalukom

clean up certificate and issuer lists and details

2021-09-06 11:13 UTC, Wawrzyn321 requested changes
Looks fine, but please add the Tooltip with `status.message` (if applies) to the statuses.

2021-09-06 12:16 UTC, Wawrzyn321 approved these changes

2021-09-07 05:29 UTC, Sawthis commented
/retest

2021-09-07 05:42 UTC, Sawthis approved these changes

2021-09-07 05:47 UTC, klaudiagrz approved these changes

2021-09-07 05:49 UTC, merged