Legal stuff links in footer
kyma-project/busola pull request #459
Opened 2021-10-12 08:47 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-10-13 10:38 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2021-10-13 12:20 UTC, dariadomagala commented on core/src/luigi-config/nav-footer.js
> +  // the footer is already here
Can't we just set the footer text as empty at the beginning to avoid it?

2021-10-14 11:15 UTC, dariadomagala approved these changes

2021-10-14 12:22 UTC, NHingerl requested changes

2021-10-14 12:22 UTC, NHingerl commented on core/src/i18n/en.yaml
> +      The chosen storage type has been overwritten by the cluster configuration from {{originalStorage}} to
```suggestion
      The chosen storage type has been overwritten by the cluster configuration from {{originalStorage}} to {{targetStorage}}.
```

Why split that sentence to two lines? Not good for translators.

2021-10-14 12:22 UTC, NHingerl commented on core/src/i18n/en.yaml
> +      {{targetStorage}}.
```suggestion
```

2021-10-14 12:22 UTC, NHingerl commented on core/src/i18n/en.yaml
> +    info: >
No. Don't split sentences, that can't be good for translation.

2021-10-14 12:22 UTC, NHingerl commented on core/src/i18n/en.yaml
> +legal:
Legal sections are alright. 

But I won't approve unless we know for sure that the translation workflow can accommodate split sentences

2021-10-14 12:43 UTC, NHingerl commented on core/src/i18n/en.yaml
> +legal:
sentences were combined again :)

2021-10-14 12:43 UTC, NHingerl approved these changes

2021-10-14 12:54 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2021-10-14 13:02 UTC, merged