Handle multiple AccessStrategies
kyma-project/busola pull request #522
Opened 2021-11-12 08:13 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-11-15 07:09 UTC, dariadomagala requested changes

2021-11-15 07:09 UTC, dariadomagala commented on core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
> +    t('api-rules.access-strategies.labels.types'),
You've changed the order of columns here

2021-11-15 07:09 UTC, dariadomagala commented on core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
> +          <InfoLabel modifier="filled">
Was the removal of `glyph` planned or was it accidental?

2021-11-15 08:33 UTC, dariadomagala submitted a review, later dismissed

2021-11-16 08:19 UTC, mmitoraj approved these changes

2021-11-16 08:22 UTC, dariadomagala approved these changes

2021-11-16 08:22 UTC, merged