Fix for DNS Entries Target dropdown
kyma-project/busola pull request #581
Opened 2021-11-18 07:43 UTC by Sawthis

**Description**

Changes proposed in this pull request:

- ...

**Related issue(s)**

2021-11-22 07:00 UTC, qbalukom requested changes

2021-11-22 07:00 UTC, qbalukom commented on core-ui/src/components/Predefined/Create/DNSEntries/DNSEntries.create.js
>          }}
This bit should be handled by DNSNameRef internally - see relevant suggestions in that component.
```suggestion
```
Similar story with `TargetRef` and `TextRef`

2021-11-22 07:00 UTC, qbalukom commented on core-ui/src/components/Predefined/Create/DNSEntries/DNSNameRef.js
>  export function DNSNameRef({ required, domain, onChange }) {
can't make a proper suggestion for the whole component, but this should make it handle ResourceForm properties correctly:
```
export function DNSNameRef({ required, ...props }) {
  const { t } = useTranslation();
  const url = `/apis/dns.gardener.cloud/v1alpha1/dnsproviders`;
  const { data } = useGetList()(url);
  useEffect(() => {
    if (data) {
      memoizedProviders = data;
    }
  }, [data]);

  const providers = memoizedProviders || data;

  const domains = (providers || [])
    .map(resource => resource.spec.domains?.include)
    ?.flat();
  const includedDomains = domains.map(domain => ({
    key: domain,
    text: domain,
  }));

  return (
    <ResourceForm.FormField
      {...props}
      required={required}
      label={t('dnsentries.labels.dns-name')}
      propertyPath="$.spec.dnsName"
      input={ResourceForm.ComboboxInput}
      options={includedDomains}
      selectionType="manual"
      key="dns-name-select"
      placeholder={t('dnsentries.placeholders.dns-name')}
    />
  );
}
```
key points:
1. pass incoming props to FormField
2. don't override `ResourceForm.ComboboxInput` - let it handle data from `input={}` by itself
3. `ResourceForm` will take care of `onChange`, `setValue`, etc.
4. any props passed to FormField but not handled get propagated to input (to organize them nicely, i like to place those _after_ the input prop)

2021-11-23 08:53 UTC, Wawrzyn321 approved these changes

2021-11-23 09:00 UTC, qbalukom approved these changes

2021-11-23 09:06 UTC, alexandra-simeonova approved these changes

2021-11-23 09:08 UTC, merged