Make the status Labels translatable
kyma-project/busola pull request #629
Opened 2021-11-30 14:21 UTC by akucharska

**Description**

Changes proposed in this pull request:

- First draft of mechanism for statuses translations
- Cover: ApiRules, Nodes (cluster overview), Functions

**Related issue(s)**

2021-12-02 14:12 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-02 14:29 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-02 14:44 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-03 12:56 UTC, qbalukom requested changes

2021-12-03 12:56 UTC, qbalukom commented on core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
> +      resourceKind={'api-rules'}
wouldn't resourceKind='api-rules' be enough here?

2021-12-03 12:56 UTC, qbalukom commented on core-ui/src/components/Clusters/views/ClusterStorageType.js
> +      resourceKind={'clusters'}
wouldn't resourceKind='clusters' be enough here?

2021-12-03 12:56 UTC, qbalukom commented on core/src/i18n/en.yaml
> +aa: s
???

2021-12-03 14:10 UTC, qbalukom approved these changes

2021-12-06 06:15 UTC, majakurcius commented on core/src/i18n/en.yaml
> +    ok: Ok
```suggestion
    ok: OK
```

2021-12-06 07:12 UTC, akucharska commented
/retest

2021-12-06 07:22 UTC, majakurcius submitted a review, later dismissed

2021-12-06 07:50 UTC, qbalukom approved these changes

2021-12-06 08:04 UTC, majakurcius approved these changes

2021-12-06 08:05 UTC, merged