Test reduced permissions
kyma-project/busola pull request #635
Opened 2021-12-01 07:41 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-12-02 07:14 UTC, Wawrzyn321 commented
Woah, it just works.
/test pre-busola-smoke-test-docker

2021-12-02 07:33 UTC, Wawrzyn321 commented
Again
/test pre-busola-smoke-test-k3s

2021-12-02 07:33 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2021-12-02 08:05 UTC, Wawrzyn321 commented
Some of the other tests failed, but `reduced perms` not.

2021-12-02 08:30 UTC, Wawrzyn321 commented
Other tests failed again.
/test pre-busola-integration-test-k3s

2021-12-02 08:57 UTC, Wawrzyn321 commented
It looks like `nkyma` has a problem with Functions - they take ages to build. I'll postpone retesting for now.

2021-12-02 11:16 UTC, dariadomagala requested changes

2021-12-02 11:16 UTC, dariadomagala commented on tests/tests/reduced-permissions.spec.js
> +function chooseComboboxOption(selector, optionText) {
Could we move this function to a shared file? This might be useful in other tests

2021-12-02 11:16 UTC, dariadomagala commented on tests/tests/reduced-permissions.spec.js
> +    // cy.contains('Clusters Overview').click();
Why is it commented out?

2021-12-02 11:16 UTC, dariadomagala commented on tests/tests/reduced-permissions.spec.js
> +  });
We should delete the cluster-wide resources at the end. We don't need hundreds of Cluster roles on our testing cluster

2021-12-02 13:46 UTC, dariadomagala approved these changes

2021-12-03 07:40 UTC, dariadomagala approved these changes

2021-12-03 08:25 UTC, dariadomagala approved these changes

2021-12-03 08:45 UTC, merged