Tooltips
kyma-project/busola pull request #699
Opened 2021-12-10 15:00 UTC by grego952

**Description**

Changes proposed in this pull request:

- add tooltips to the CRDs

2021-12-12 20:08 UTC, grego952 commented
/retest

2021-12-13 11:31 UTC, majakurcius commented on core/src/i18n/en.yaml
> +    skipped: Skipped creating a resource.
```suggestion
    skipped: Skipped creating the resource.
```

2021-12-13 11:31 UTC, majakurcius commented on core/src/i18n/en.yaml
> +    building: Waiting for the image to be build.
```suggestion
    building: Waiting for the image to be built.
```

But perhaps I'd shorten it to `Waiting for the image to build`.

2021-12-13 11:31 UTC, majakurcius commented on core/src/i18n/en.yaml
> +    deploying: Deploying function.
```suggestion
    deploying: Deploying the Function.
```
We [capitalize `Function`](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/02-style-and-terminology.md#capitalized-terms) as a proper name.

2021-12-13 11:44 UTC, majakurcius submitted a review, later dismissed

2021-12-13 14:10 UTC, dariadomagala commented
/retest

2021-12-14 06:55 UTC, majakurcius submitted a review, later dismissed

2021-12-14 08:42 UTC, grego952 commented
/test pre-busola-integration-test-k3s

2021-12-14 09:20 UTC, grego952 commented
/test pre-busola-integration-test-k3s

2021-12-14 09:46 UTC, grego952 commented
/test pre-busola-integration-test-k3s

2021-12-14 10:51 UTC, Sawthis commented
/retest

2021-12-15 04:34 UTC, qbalukom requested changes

2021-12-15 04:34 UTC, qbalukom commented on shared/components/TooltipBadge/TooltipBadge.js
> +      style={{ whiteSpace: 'nowrap' }}
why this mix of css and `style=`? this should be moved to css file as well.

2021-12-15 09:10 UTC, qbalukom approved these changes

2021-12-15 09:10 UTC, qbalukom commented
/retest

2021-12-15 09:30 UTC, qbalukom commented
/retest

2021-12-16 07:31 UTC, majakurcius submitted a review, later dismissed

2021-12-16 11:07 UTC, majakurcius approved these changes

2021-12-16 11:10 UTC, Sawthis approved these changes

2021-12-16 11:11 UTC, merged