Ingresses
kyma-project/busola pull request #714
Opened 2021-12-14 15:41 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-12-15 07:07 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-15 12:37 UTC, Wawrzyn321 commented on core-ui/src/components/Predefined/List/Ingresses.list.js
> +      return '-';
Please use EMPTY_TEXT_PLACEHOLDER.

2021-12-15 12:38 UTC, Wawrzyn321 commented on core/src/i18n/en.yaml
> +    load-balancers: LoadBalancers
```suggestion
    load-balancers: Load Balancers
```
...?

2021-12-15 13:13 UTC, Wawrzyn321 commented on tests/tests/test-ingresses.spec.js
> +        console.log('INGRESS', INGRESS);
```suggestion
```

2021-12-15 13:13 UTC, Wawrzyn321 commented on tests/tests/test-ingresses.spec.js
> +          .type(INGRESS, { parseSpecialCharSequences: false });
```suggestion
          .paste({
            pastePayload: INGRESS,
          });
```

2021-12-15 13:16 UTC, Wawrzyn321 requested changes
This translation is missing
![image](https://user-images.githubusercontent.com/10504661/146193259-642ffdf5-4206-404c-8d41-36ce2979b3d0.png)

2021-12-15 13:19 UTC, Wawrzyn321 commented on core-ui/src/components/Predefined/Details/Ingress/RowComponent.js
> +export const RowComponent = ({ name, value }) => (
I believe we can use `LayoutPanelRow` for that (well, it has no ':'). Besides, `item-wrapper` class is not defined anywhere - AFAIK it has been renamed to `break-word` (from root index.scss).

2021-12-15 15:16 UTC, Wawrzyn321 submitted a review, later dismissed

2021-12-15 15:16 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2021-12-16 06:34 UTC, grego952 commented on core/src/i18n/en.yaml
> +  description: <0>Ingress</0> exposes HTTP and HTTPS routes from outside the cluster to services within the cluster. Traffic routing is controlled by rules defined on the Ingress resource.
```suggestion
  description: <0>Ingress</0> describes the routing rules for traffic to services within a cluster. The routing is managed by the Ingress resource.
```

2021-12-16 07:41 UTC, Wawrzyn321 approved these changes

2021-12-16 08:03 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 08:29 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 09:04 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 09:16 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 10:01 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 11:33 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2021-12-16 13:26 UTC, grego952 commented
/lgtm

2021-12-16 13:29 UTC, Wawrzyn321 submitted a review, later dismissed

2021-12-16 13:52 UTC, majakurcius commented on core/src/i18n/en.yaml
> +    apiGroup: ApiGroup
```suggestion
    apiGroup: APIGroup
```
`API` is an acronym for `Application Programming Interface`, unless there's a reason why it's spelt this way here that I'm not aware of.

2021-12-16 13:57 UTC, majakurcius submitted a review, later dismissed

2021-12-16 14:05 UTC, majakurcius approved these changes

2021-12-16 14:21 UTC, akucharska commented
/test pre-busola-smoke-test-docker

2021-12-16 14:29 UTC, Wawrzyn321 approved these changes

2021-12-16 14:29 UTC, merged