Adjust statuses and tooltips for functions and pods
kyma-project/busola pull request #748
Opened 2021-12-27 09:58 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-12-27 13:19 UTC, Wawrzyn321 requested changes
(writing here in case me forgets)
We could remove full stops after error statuses, so we have `Error: message` instead of `Error.: message`.

2021-12-28 08:18 UTC, Wawrzyn321 approved these changes

2021-12-28 11:02 UTC, dariadomagala commented
/retest

2021-12-28 12:21 UTC, mmitoraj reviewed
I added some suggestions. I have a question regarding the full stops a the end of some sentences. Maybe you could show me the tooltips in the UI so that we can confirm that it displays fine?

2021-12-28 12:21 UTC, mmitoraj commented on core/src/i18n/en.yaml
> +    completed: Pod has completed successfully.
What do you mean? Has it restarted successfully?

2021-12-28 12:21 UTC, mmitoraj commented on core/src/i18n/en.yaml
> +    evicted: Pod has been evicted.
```suggestion
    evicted: Pod has been removed.
```

2021-12-28 12:21 UTC, mmitoraj commented on core/src/i18n/en.yaml
> +    podinitializing: Pod is being initialized.
```suggestion
    podinitializing: Initializing the Pod.
```

2021-12-28 12:21 UTC, mmitoraj commented on core/src/i18n/en.yaml
> +    terminating: Pod is being terminated.
```suggestion
    terminating: Terminating the Pod.
```

2021-12-29 10:32 UTC, Wawrzyn321 submitted a review, later dismissed

2021-12-29 10:59 UTC, Wawrzyn321 approved these changes

2021-12-29 11:06 UTC, mmitoraj approved these changes

2021-12-29 11:24 UTC, Wawrzyn321 commented
/retest

2021-12-29 11:44 UTC, merged