Feature/create event sub
kyma-project/busola pull request #751
Opened 2021-12-28 08:31 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-12-28 08:31 UTC, mrCherry97 commented
/test all

2021-12-28 08:33 UTC, mrCherry97 commented
/test all

2021-12-28 10:13 UTC, mrCherry97 commented
/test all

2021-12-28 10:21 UTC, mrCherry97 commented
/test all

2021-12-28 10:38 UTC, mrCherry97 commented
/test all

2021-12-28 11:40 UTC, Lyczeq commented
/retest

2021-12-28 13:11 UTC, mrCherry97 commented on tests/tests/in-cluster-eventing.spec.js
> +    cy.wait(4000);
I have to delete it, have to do it later.

2021-12-29 07:10 UTC, akucharska requested changes
We should not mark missing fields with red outline on form opening. It should be done when we loose focus on the input
<img width="1102" alt="Screen Shot 2021-12-29 at 08 06 18" src="https://user-images.githubusercontent.com/20790348/147636230-dfa6df21-0f7e-4a37-8289-b7dcef99beb0.png">

2021-12-29 10:11 UTC, akucharska submitted a review, later dismissed

2021-12-29 10:19 UTC, klaudiagrz commented on core/src/i18n/en.yaml
> +    empty-event-types: You must provide at least one Event Type.
```suggestion
    empty-event-types: You must provide at least one Event type.
```

2021-12-29 10:19 UTC, klaudiagrz submitted a review, later dismissed

2021-12-29 10:19 UTC, mrCherry97 commented
/retest

2021-12-29 10:35 UTC, mrCherry97 commented
/retest

2021-12-29 10:47 UTC, mrCherry97 commented
/retest

2021-12-29 14:26 UTC, mrCherry97 commented
"So, for now unfortunately it is 7 segments constraint, we try to fix that soonish, it’s already in our backlog" Info from Tunas, we have to discuss about solution of `Event type`

2021-12-30 10:14 UTC, klaudiagrz commented on core/src/i18n/en.yaml
> +    event-name: Provide a name for your Event.
```suggestion
    event-name: Provide a name for your Event. The name must consist of at least two parts divided by a dot.
```

2021-12-30 10:15 UTC, klaudiagrz approved these changes

2021-12-30 10:37 UTC, mrCherry97 commented
/retest

2021-12-30 10:43 UTC, mrCherry97 commented
/retest

2021-12-30 11:07 UTC, akucharska approved these changes

2021-12-30 11:08 UTC, merged