Hide read only lines from editor
kyma-project/busola pull request #765
Opened 2022-01-03 07:03 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Add button that can hide/show managedFields and status

**Related issue(s)**

2022-01-03 08:03 UTC, akucharska commented
/test pre-busola-integration-test-k3s

2022-01-03 10:15 UTC, dariadomagala requested changes
* have the 'show read-only fields' option on
* hide `managedFields` (in the editor, not using the show/hide button)
* click 'hide read-only fields' button
* 💥 whole `metadata` field is also hidden

2022-01-04 07:05 UTC, dariadomagala approved these changes

2022-01-04 07:29 UTC, akucharska commented
/test all

2022-01-04 08:38 UTC, mmitoraj approved these changes

2022-01-04 08:51 UTC, dariadomagala approved these changes

2022-01-04 08:52 UTC, merged