Repair informations with bad inputs
kyma-project/busola pull request #769
Opened 2022-01-03 13:49 UTC by mrCherry97

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-01-03 14:14 UTC, mmitoraj submitted a review, later dismissed

2022-01-04 15:42 UTC, Lyczeq commented
/retest

2022-01-05 08:50 UTC, mrCherry97 commented
/retest

2022-01-05 10:06 UTC, Lyczeq commented
/retest

2022-01-05 10:07 UTC, dariadomagala requested changes
* Why there is no validation error? 
* Event Type is a list so I believe it should be Event Type**s**
* I believe that on the Functions view, the dropdown with service chooser should be disabled. The subscription won't work for this function if we choose a different service

2022-01-05 10:07 UTC, dariadomagala commented on core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
>              `https://${serviceName}.${namespace}.svc.cluster.local`,
```suggestion
            `http://${serviceName}.${namespace}.svc.cluster.local`,
```

2022-01-05 10:29 UTC, dariadomagala commented on core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
>    useEffect(() => {
do we need this useEffect? wouldn't `setValue` that we have in line 154 be enough?

2022-01-05 11:00 UTC, dariadomagala commented on core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
> +        title={t('subscription.create.labels.event-type')}
EventS typeS? In the advanced view, it's a list so it should be plural

2022-01-05 11:50 UTC, dariadomagala approved these changes

2022-01-05 11:56 UTC, mmitoraj approved these changes

2022-01-05 12:16 UTC, merged