Improve validation
kyma-project/busola pull request #816
Opened 2022-01-17 00:35 UTC by qbalukom

2022-01-18 08:09 UTC, Wawrzyn321 commented
/retest

2022-01-18 08:41 UTC, Wawrzyn321 commented
/retest

2022-01-19 11:00 UTC, dariadomagala requested changes
1. When I try to add a new filter:
<img width="470" alt="Screen Shot 2022-01-19 at 11 56 23" src="https://user-images.githubusercontent.com/40663133/150116727-4ed599ab-68b7-4fb9-8cd0-a776ef20db85.png">
2. We should also add validation in the simple view for the event name to consist of a dot.
3. Should we disable an option to use dashes in the app name or should we allow it, and the backend will change it?

2022-01-19 12:57 UTC, Wawrzyn321 commented
1. Fixed
2. Done
3. I have no idea, backend regex does not mention '-', but subscription created with dash is errorless... I've added it to whitelist.

2022-01-19 13:23 UTC, Wawrzyn321 commented
/retest

2022-01-19 13:28 UTC, dariadomagala reviewed
If I add a new filter, the 'Create' button is still active, even tho the new filter with a default value (so only a prefix), shouldn't be considered valid.

2022-01-19 13:28 UTC, dariadomagala commented on core/src/i18n/en.yaml
> +    event-name-segments: Event name must consist of at least 2 non-empty segments, separated by "." character.
Wouldn't that be simplier?
```suggestion
    event-name-segments: Event name must consist of at least 2 non-empty segments, separated by a dot.
```

2022-01-19 13:52 UTC, dariadomagala submitted a review, later dismissed

2022-01-19 13:57 UTC, grego952 submitted a review, later dismissed

2022-01-19 13:59 UTC, dariadomagala submitted a review, later dismissed

2022-01-19 14:14 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2022-01-19 14:32 UTC, Wawrzyn321 commented
/retest

2022-01-20 10:27 UTC, Wawrzyn321 commented
/test pre-busola-smoke-test-docker

2022-01-20 10:37 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2022-01-20 10:58 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2022-01-20 11:31 UTC, Wawrzyn321 commented
/test pre-busola-integration-test-k3s

2022-01-20 11:52 UTC, grego952 approved these changes

2022-01-20 11:56 UTC, dariadomagala approved these changes

2022-01-20 11:58 UTC, merged