Add possibility to disable sidecars for jobs and cronjobs
kyma-project/busola pull request #940
Opened 2022-02-09 11:29 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Add possibility to disable sidecars for jobs and cronjobs

**Related issue(s)**

2022-02-09 11:55 UTC, akucharska commented
/retest

2022-02-09 12:23 UTC, Wawrzyn321 commented on core/src/i18n/en.yaml
> +    disable-sidecar: Disable sidecar
Maybe remove that translation and use the one from `jobs` section? Common stuff for Jobs and CronJobs is here anyway (see `ContainerSection.js`, which uses only `jobs.` prefixed translation keys and is used for both Jobs and CJs).

2022-02-09 12:24 UTC, Wawrzyn321 requested changes
View breaks on entering the CronJob create modal
<img width="702" alt="image" src="https://user-images.githubusercontent.com/10504661/153200563-829ad771-0892-459d-8c3b-9d9a36bfcfe3.png">

2022-02-09 12:26 UTC, Wawrzyn321 commented on core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
> +      });
Maybe use
```
jp.value(cronJob, 'turbo-long-path', jobTemplateAnnotations);
setCronJob({...cronJob});
```
?

2022-02-10 07:34 UTC, Wawrzyn321 approved these changes

2022-02-10 08:10 UTC, grego952 approved these changes

2022-02-10 08:11 UTC, merged