Add error boundary to monaco editors
kyma-project/busola pull request #949
Opened 2022-02-09 14:06 UTC by wchrapka

**Description**

Adds Error boundary component for monaco editors

**Related issue(s)**

Resolves #909

2022-02-10 11:39 UTC, wchrapka commented
/test pre-busola-integration-test-k3s

2022-02-11 08:06 UTC, dariadomagala requested changes
We don't have the boundaries for the 'add cluster' editor.

2022-02-11 08:06 UTC, dariadomagala commented
Also, could we add a test (might be just a unit test) for that?

2022-02-11 12:34 UTC, wchrapka commented on shared/components/ErrorBoundary/ErrorBoundary.js
> +            {this.props.t('err-boundary.restored-initial-form')}
option added

2022-02-14 08:54 UTC, Wawrzyn321 requested changes
Would you kindly fix this case? When I paste such "kubeconfig", the error boundary is triggered, but then the error show up anyway:
```apiVersion: v1
kind: Config
current-context: shoot--hasselhoff--kmain
contexts:
  - name: shoot--hasselhoff--kmain
    context:
      cluster: shoot--hasselhoff--kmain
      user: shoot--hasselhoff--kmain-token
clusters:
  - name: shoot--hasselhoff--kmain
    cluster:
      server: https://api.kmain.hasselhoff.shoot.canary.k8s-hana.ondemand.com
      certificate-authority-data: 'yadadada'
users: 2 
```

2022-02-14 14:34 UTC, wchrapka commented
> Would you kindly fix this case? When I paste such "kubeconfig", the error boundary is triggered, but then the error show up anyway:
> 
> ```
> kind: Config
> current-context: shoot--hasselhoff--kmain
> contexts:
>   - name: shoot--hasselhoff--kmain
>     context:
>       cluster: shoot--hasselhoff--kmain
>       user: shoot--hasselhoff--kmain-token
> clusters:
>   - name: shoot--hasselhoff--kmain
>     cluster:
>       server: https://api.kmain.hasselhoff.shoot.canary.k8s-hana.ondemand.com
>       certificate-authority-data: 'yadadada'
> users: 2 
> ```

That's the expected behavior on dev server, I haven't observed this issue in other envrionments. Could you describe how to reproduce?

2022-02-15 07:43 UTC, Wawrzyn321 approved these changes

2022-02-15 08:04 UTC, wchrapka commented
/test pre-busola-integration-test-k3s

2022-02-15 08:17 UTC, grego952 commented on core/src/i18n/en.yaml
> +  go-back: Go Back
```suggestion
  go-back: Go back
```

2022-02-15 08:17 UTC, grego952 commented on core/src/i18n/en.yaml
> +  restored-initial-form: Something went wrong, we restored the initial form for you.
```suggestion
  restored-initial-form: Something went wrong We restored the initial form for you.
```

2022-02-15 08:34 UTC, Wawrzyn321 approved these changes

2022-02-15 10:49 UTC, grego952 approved these changes

2022-02-15 11:52 UTC, merged