Introduce Network Policies feature
kyma-project/busola pull request #963
Opened 2022-02-15 12:52 UTC by wchrapka

**Description**

Adds the sets of Network Policy views to Network and Discovery menu

**Related issue(s)**

Solves #948

2022-02-15 13:18 UTC, grego952 commented on core/src/i18n/en.yaml
> +  description: <0>Network Policy</0> allows you to specify how a pod is allowed to communicate with various network entities.
```suggestion
  description: <0>Network Policy</0> allows you to control how a Pod communicates with different network entities.
```

2022-02-15 13:32 UTC, grego952 approved these changes

2022-02-15 15:18 UTC, wchrapka commented
/test pre-busola-integration-test-k3s

2022-02-16 12:33 UTC, Wawrzyn321 commented on core-ui/src/components/Predefined/Details/NetworkPolicy/LabelSelector.js
> +        data-testid="hpa-spec-ref"
```suggestion
```

2022-02-16 12:41 UTC, Wawrzyn321 commented on core-ui/src/components/Predefined/Details/NetworkPolicy/Peers.js
> +              />
```suggestion
                value={<Tokens tokens={peer.ipBlock?.except} />}
```

2022-02-16 12:46 UTC, Wawrzyn321 requested changes
Would you kindly list also Pods affected by a policy?

2022-02-16 14:45 UTC, Wawrzyn321 approved these changes

2022-02-17 07:25 UTC, grego952 approved these changes

2022-02-17 07:26 UTC, merged