Prometheus stats
kyma-project/busola pull request #964
Opened 2022-02-15 14:12 UTC by qbalukom

2022-02-17 08:13 UTC, Wawrzyn321 requested changes
Tick value labels are wrong when I change the timeframe.

https://user-images.githubusercontent.com/10504661/154433003-e77518b4-bfb6-47fe-a39d-10ed7be9bbf2.mov

2022-02-17 08:16 UTC, Wawrzyn321 commented
Would you kindly make it consistent?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/10504661/154433575-d620c299-6b58-4cc8-b778-06f949ed4c1c.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/10504661/154433611-3142be86-1af9-4936-a5e9-b0610f3235f0.png">
(both round to e.g. 2 places and display the unit all the time)

2022-02-17 08:24 UTC, Wawrzyn321 commented
Would it be possible to work on text resolution? It isn't very crisp, compared to normal text
<img width="598" alt="image" src="https://user-images.githubusercontent.com/10504661/154435039-6ebd05e2-197f-435e-b4f3-978e6b679239.png">

2022-02-18 11:46 UTC, Wawrzyn321 approved these changes

2022-02-18 12:18 UTC, grego952 approved these changes

2022-02-18 12:28 UTC, merged